// Auto-generated test data from sites/*.js test sections at bottom.
var nodemapper_tests = [
  ["urlToGraphNode", "http://www.amazon.com/gp/pdp/profile/A2Q1GI13N0TVRC", "sgn://amazon.com/?pk=A2Q1GI13N0TVRC"],
  ["urlToGraphNode", "http://amazon.com/gp/pdp/profile/A2Q1GI13N0TVRC", "sgn://amazon.com/?pk=A2Q1GI13N0TVRC"],
  ["urlToGraphNode", "http://www.amazon.co.uk/gp/pdp/profile/A2Q1GI13N0TVRC", "sgn://amazon.com/?pk=A2Q1GI13N0TVRC"],
  ["urlToGraphNode", "http://www.amazon.com/rss/people/A2Q1GI13N0TVRC/reviews", "sgn://amazon.com/?pk=A2Q1GI13N0TVRC"],
  ["urlFromGraphNode", "sgn://amazon.com/?pk=A2Q1GI13N0TVRC", "profile", "http://www.amazon.com/gp/pdp/profile/A2Q1GI13N0TVRC"],
  ["urlToGraphNode", "http://www.amazon.com/gp/pdp/profile/A2Q1GI13N0TVRC", "sgn://amazon.com/?pk=A2Q1GI13N0TVRC"],
  ["urlFromGraphNode", "sgn://amazon.com/?pk=A2Q1GI13N0TVRC", "rss", "http://www.amazon.com/rss/people/A2Q1GI13N0TVRC/reviews"],
  ["urlToGraphNode", "http://www.amazon.com/rss/people/A2Q1GI13N0TVRC/reviews", "sgn://amazon.com/?pk=A2Q1GI13N0TVRC"],
  ["urlToGraphNode", "aim:goim?message=Hi!+I+found+you+on+Xxxx...&screenname=Foo%20Bar", "sgn://aol.com/?ident=foobar"],
  ["urlToGraphNode", "aim:GoIM?screenname=fooBar", "sgn://aol.com/?ident=foobar"],
  ["urlToGraphNode", "aim:goim?Screenname=foo+Bar", "sgn://aol.com/?ident=foobar"],
  ["urlToGraphNode", "aim:goim?screenname=foo%20bar", "sgn://aol.com/?ident=foobar"],
  ["urlToGraphNode", "aim:fooBar", "sgn://aol.com/?ident=foobar"],
  ["urlToGraphNode", "aim:foo+Bar", "sgn://aol.com/?ident=foobar"],
  ["urlToGraphNode", "http://www.aimpages.com/foobar/profile.html", "sgn://aol.com/?ident=foobar"],
  ["urlToGraphNode", "http://www.aimpages.com//foobar/profile.html", "sgn://aol.com/?ident=foobar"],
  ["urlToGraphNode", "http://www.aimpages.com/foobar/", "sgn://aol.com/?ident=foobar"],
  ["urlToGraphNode", "http://www.aimpages.com/foo+bar/", "sgn://aol.com/?ident=foobar"],
  ["urlToGraphNode", "http://www.aimpages.com/foobar", "sgn://aol.com/?ident=foobar"],
  ["urlToGraphNode", "http://openid.aol.com/foobar", "sgn://aol.com/?ident=foobar"],
  ["urlToGraphNode", "http://openid.aol.com/foobar/", "sgn://aol.com/?ident=foobar"],
  ["urlToGraphNode", "http://profiles.aim.com/foobar", "sgn://aol.com/?ident=foobar"],
  ["urlFromGraphNode", "sgn://aol.com/?ident=foobar", "openid", "http://openid.aol.com/foobar"],
  ["urlToGraphNode", "http://openid.aol.com/foobar", "sgn://aol.com/?ident=foobar"],
  ["urlFromGraphNode", "sgn://aol.com/?ident=foobar", "chat", "aim:GoIM?screenname=foobar"],
  ["urlToGraphNode", "aim:GoIM?screenname=foobar", "sgn://aol.com/?ident=foobar"],
  ["urlFromGraphNode", "sgn://aol.com/?ident=foobar", "profile", "http://profiles.aim.com/foobar"],
  ["urlToGraphNode", "http://profiles.aim.com/foobar", "sgn://aol.com/?ident=foobar"],
  ["urlToGraphNode", "http://pictures.aol.com/galleries/josephsmarr", "sgn://pictures.aol.com/?ident=josephsmarr"],
  ["urlFromGraphNode", "sgn://pictures.aol.com/?ident=josephsmarr", "profile", "http://pictures.aol.com/galleries/josephsmarr"],
  ["urlToGraphNode", "http://pictures.aol.com/galleries/josephsmarr", "sgn://pictures.aol.com/?ident=josephsmarr"],
  ["urlFromGraphNode", "sgn://pictures.aol.com/?ident=josephsmarr", "atom", "http://pictures.aol.com/galleries/josephsmarr/atom.xml"],
  ["urlToGraphNode", "http://pictures.aol.com/galleries/josephsmarr/atom.xml", "sgn://pictures.aol.com/?ident=josephsmarr"],
  ["urlToGraphNode", "http://www.blogger.com/profile/123", "sgn://blogger.com/?pk=123"],
  ["urlFromGraphNode", "sgn://blogger.com/?pk=123", "profile", "http://www.blogger.com/profile/123"],
  ["urlToGraphNode", "http://www.blogger.com/profile/123", "sgn://blogger.com/?pk=123"],
  ["urlToGraphNode", "http://foo.blogspot.com/", "sgn://blogspot.com/?ident=foo"],
  ["urlToGraphNode", "http://www.foo.blogspot.com/", "sgn://blogspot.com/?ident=foo"],
  ["urlToGraphNode", "http://foo.blogspot.com/path/blah", "sgn://blogspot.com/?ident=foo"],
  ["urlFromGraphNode", "sgn://blogspot.com/?ident=foo", "content", "http://foo.blogspot.com/"],
  ["urlToGraphNode", "http://foo.blogspot.com/", "sgn://blogspot.com/?ident=foo"],
  ["urlFromGraphNode", "sgn://blogspot.com/?ident=foo", "blog", "http://foo.blogspot.com/"],
  ["urlToGraphNode", "http://foo.blogspot.com/", "sgn://blogspot.com/?ident=foo"],
  ["urlFromGraphNode", "sgn://blogspot.com/?ident=foo", "atom", "http://foo.blogspot.com/feeds/posts/default"],
  ["urlToGraphNode", "http://foo.blogspot.com/feeds/posts/default", "sgn://blogspot.com/?ident=foo"],
  ["urlFromGraphNode", "sgn://blogspot.com/?ident=foo", "rss", "http://foo.blogspot.com/feeds/posts/default?alt=rss"],
  ["urlToGraphNode", "http://foo.blogspot.com/feeds/posts/default?alt=rss", "sgn://blogspot.com/?ident=foo"],
  ["urlToGraphNode", "http://www.facebook.com/profile.php?id=500033387", "sgn://facebook.com/?pk=500033387"],
  ["urlToGraphNode", "http://fr.facebook.com/profile.php?id=500033387", "sgn://facebook.com/?pk=500033387"],
  ["urlToGraphNode", "http://fr.facebook.ca/profile.php?id=500033387", "sgn://facebook.com/?pk=500033387"],
  ["urlToGraphNode", "http://www.facebook.com/people/Brad_Fitzpatrick/500033387", "sgn://facebook.com/?ident=Brad_Fitzpatrick/500033387"],
  ["urlToGraphNode", "http://www.facebook.com/people/Brad-Fitzpatrick/500033387", "sgn://facebook.com/?ident=Brad-Fitzpatrick/500033387"],
  ["urlToGraphNode", "http://www.facebook.com/p/Brad_Fitzpatrick/500033387", "sgn://facebook.com/?ident=Brad_Fitzpatrick/500033387"],
  ["urlToGraphNode", "http://facebook.com/p/Brad_Fitzpatrick/500033387", "sgn://facebook.com/?ident=Brad_Fitzpatrick/500033387"],
  ["urlToGraphNode", "http://washington.facebook.com/profile.php?id=123&ref=np", "sgn://facebook.com/?pk=123"],
  ["urlFromGraphNode", "sgn://facebook.com/?pk=500033387", "profile", "http://www.facebook.com/profile.php?id=500033387"],
  ["urlToGraphNode", "http://www.facebook.com/profile.php?id=500033387", "sgn://facebook.com/?pk=500033387"],
  ["urlFromGraphNode", "sgn://facebook.com/?ident=Brad_Fitzpatrick/500033387", "profile", "http://www.facebook.com/people/Brad_Fitzpatrick/500033387"],
  ["urlToGraphNode", "http://www.facebook.com/people/Brad_Fitzpatrick/500033387", "sgn://facebook.com/?ident=Brad_Fitzpatrick/500033387"],
  ["urlToGraphNode", "http://www.new.facebook.com/people/Foo_Bar/123", "sgn://facebook.com/?ident=Foo_Bar/123"],
  ["urlToGraphNode", "http://www.new.facebook.com/home.php#/profile.php?id=123", "sgn://facebook.com/?pk=123"],
  ["urlToGraphNode", "http://www.facebook.com/group.php", "http://www.facebook.com/group.php"],
  ["urlToGraphNode", "http://www.facebook.com/people", "http://www.facebook.com/people"],
  ["urlToGraphNode", "http://www.facebook.com/help", "http://www.facebook.com/help"],
  ["urlToGraphNode", "http://www.facebook.com/pages/foo", "http://www.facebook.com/pages/foo"],
  ["urlToGraphNode", "http://www.facebook.com/sarahpalin", "sgn://facebook.com/?ident=sarahpalin"],
  ["urlToGraphNode", "http://www.facebook.com/sarahpalin/", "sgn://facebook.com/?ident=sarahpalin"],
  ["urlToGraphNode", "http://www.facebook.com/sarahpalin?v=info", "sgn://facebook.com/?ident=sarahpalin"],
  ["urlToGraphNode", "http://ru.facebook.com/sarahpalin", "sgn://facebook.com/?ident=sarahpalin"],
  ["urlToGraphNode", "http://www.facebook.com/blaise.dipersia", "sgn://facebook.com/?ident=blaisedipersia"],
  ["urlToGraphNode", "http://www.facebook.com/greg", "sgn://facebook.com/?ident=greg"],
  ["urlToGraphNode", "http://www.facebook.com/AdamLambert", "sgn://facebook.com/?ident=adamlambert"],
  ["urlFromGraphNode", "sgn://facebook.com/?ident=sarahpalin", "profile", "http://www.facebook.com/sarahpalin"],
  ["urlToGraphNode", "http://www.facebook.com/sarahpalin", "sgn://facebook.com/?ident=sarahpalin"],
  ["urlToGraphNode", "http://www.facebook.com/BrA-D.F..iTz", "sgn://facebook.com/?ident=bradfitz"],
  ["urlToGraphNode", "http://www.flickr.com/people/crucially", "sgn://flickr.com/?ident=crucially"],
  ["urlToGraphNode", "http://www.flickr.com/people/crucially/", "sgn://flickr.com/?ident=crucially"],
  ["urlToGraphNode", "http://www.flickr.com/photos/crucially", "sgn://flickr.com/?ident=crucially"],
  ["urlToGraphNode", "http://www.flickr.com/photos/crucially/", "sgn://flickr.com/?ident=crucially"],
  ["urlToGraphNode", "http://www.flickr.com/photos/15738836@N00/", "sgn://flickr.com/?pk=15738836@N00"],
  ["urlToGraphNode", "http://www.flickr.com/people/15738836@N00/", "sgn://flickr.com/?pk=15738836@N00"],
  ["urlFromGraphNode", "sgn://flickr.com/?ident=crucially", "profile", "http://www.flickr.com/people/crucially/"],
  ["urlToGraphNode", "http://www.flickr.com/people/crucially/", "sgn://flickr.com/?ident=crucially"],
  ["urlFromGraphNode", "sgn://flickr.com/?ident=crucially", "content", "http://www.flickr.com/photos/crucially/"],
  ["urlToGraphNode", "http://www.flickr.com/photos/crucially/", "sgn://flickr.com/?ident=crucially"],
  ["urlFromGraphNode", "sgn://flickr.com/?ident=crucially", "addfriend", "http://www.flickr.com/people/crucially/relationship/"],
  ["urlToGraphNode", "http://www.flickr.com/people/crucially/relationship/", "sgn://flickr.com/?ident=crucially"],
  ["urlFromGraphNode", "sgn://flickr.com/?pk=15738836@N00", "rss", "http://api.flickr.com/services/feeds/photos_public.gne?id=15738836@N00&lang=en-us&format=rss_200"],
  ["urlToGraphNode", "http://api.flickr.com/services/feeds/photos_public.gne?id=15738836@N00&lang=en-us&format=rss_200", "sgn://flickr.com/?pk=15738836@N00"],
  ["urlFromGraphNode", "sgn://flickr.com/?pk=15738836@N00", "atom", "http://api.flickr.com/services/feeds/photos_public.gne?id=15738836@N00&lang=en-us&format=atom"],
  ["urlToGraphNode", "http://api.flickr.com/services/feeds/photos_public.gne?id=15738836@N00&lang=en-us&format=atom", "sgn://flickr.com/?pk=15738836@N00"],
  ["urlFromGraphNode", "sgn://flickr.com/?pk=15738836@N00", "content", "http://www.flickr.com/photos/15738836@N00/"],
  ["urlToGraphNode", "http://www.flickr.com/photos/15738836@N00/", "sgn://flickr.com/?pk=15738836@N00"],
  ["urlFromGraphNode", "sgn://flickr.com/?pk=15738836@N00", "profile", "http://www.flickr.com/people/15738836@N00/"],
  ["urlToGraphNode", "http://www.flickr.com/people/15738836@N00/", "sgn://flickr.com/?pk=15738836@N00"],
  ["urlToGraphNode", "http://www.flickr.com/photos/84536344%40N00/", "sgn://flickr.com/?pk=84536344@N00"],
  ["pairToGraphNode", "flickr.com", "brad@danga.com", ""],
  ["urlToGraphNode", "http://www.flickr.com/people/hyph-enated", "sgn://flickr.com/?ident=hyph-enated"],
  ["urlFromGraphNode", "sgn://flickr.com/?ident=hyph-enated", "content", "http://www.flickr.com/photos/hyph-enated/"],
  ["urlToGraphNode", "http://www.flickr.com/photos/hyph-enated/", "sgn://flickr.com/?ident=hyph-enated"],
  ["urlToGraphNode", "http://flickr.com/photos/15738836@N00/with/3026663345/", "sgn://flickr.com/?pk=15738836@N00"],
  ["urlToGraphNode", "http://flickr.com/photos/15738836@N00/page3/", "sgn://flickr.com/?pk=15738836@N00"],
  ["urlToGraphNode", "http://www.flickr.com/people/15738836@N00/contacts", "sgn://flickr.com/?pk=15738836@N00"],
  ["urlToGraphNode", "http://flickr.com/photos/crucially/with/3026663345/", "sgn://flickr.com/?ident=crucially"],
  ["urlToGraphNode", "http://flickr.com/photos/crucially/page3/", "sgn://flickr.com/?ident=crucially"],
  ["urlToGraphNode", "http://www.flickr.com/people/crucially/contacts", "sgn://flickr.com/?ident=crucially"],
  ["urlToGraphNode", "http://www.flickr.com/people/crucially/contacts/?page=2&filter=default", "sgn://flickr.com/?ident=crucially"],
  ["urlToGraphNode", "http://www.flickr.com/photos/crucially/sets/", "sgn://flickr.com/?ident=crucially"],
  ["urlToGraphNode", "http://www.flickr.com/photos/crucially/favorites/", "sgn://flickr.com/?ident=crucially"],
  ["urlToGraphNode", "http://www.flickr.com/photos/crucially/page2/", "sgn://flickr.com/?ident=crucially"],
  ["urlToGraphNode", "http://www.flickr.com/photos/crucially/map/", "sgn://flickr.com/?ident=crucially"],
  ["urlToGraphNode", "http://www.flickr.com/photos/crucially/show/", "sgn://flickr.com/?ident=crucially"],
  ["urlToGraphNode", "http://flickr.com/hyph-enated", "sgn://flickr.com/?ident=hyph-enated"],
  ["urlToGraphNode", "http://flickr.com/bob", "sgn://flickr.com/?ident=bob"],
  ["urlToGraphNode", "http://flickr.com/photos", "http://flickr.com/photos"],
  ["urlToGraphNode", "http://flickr.com/groups", "http://flickr.com/groups"],
  ["urlToGraphNode", "http://flickr.com/search", "http://flickr.com/search"],
  ["urlToGraphNode", "http://flickr.com/places", "http://flickr.com/places"],
  ["urlToGraphNode", "http://flickr.com/people", "http://flickr.com/people"],
  ["urlToGraphNode", "http://flickr.com/photo", "http://flickr.com/photo"],
  ["urlToGraphNode", "http://flickr.com/explore", "http://flickr.com/explore"],
  ["urlToGraphNode", "http://flickr.com/photo_zoom", "http://flickr.com/photo_zoom"],
  ["urlToGraphNode", "http://flickr.com/commons", "http://flickr.com/commons"],
  ["urlToGraphNode", "http://flickr.com/services", "http://flickr.com/services"],
  ["urlToGraphNode", "http://flickr.com/groups_topics", "http://flickr.com/groups_topics"],
  ["urlToGraphNode", "http://friendfeed.com/ade", "sgn://friendfeed.com/?ident=ade"],
  ["urlToGraphNode", "http://www.friendfeed.com/ade", "sgn://friendfeed.com/?ident=ade"],
  ["urlToGraphNode", "http://friendfeed.com/daveman692/comments", "sgn://friendfeed.com/?ident=daveman692"],
  ["urlToGraphNode", "http://friendfeed.com/daveman692?num=30", "sgn://friendfeed.com/?ident=daveman692"],
  ["urlToGraphNode", "http://friendfeed.com/daveman692?service=blog", "sgn://friendfeed.com/?ident=daveman692"],
  ["urlToGraphNode", "http://friendfeed.com/daveman692?service=digg", "sgn://friendfeed.com/?ident=daveman692"],
  ["urlToGraphNode", "http://friendfeed.com/daveman692?service=flickr", "sgn://friendfeed.com/?ident=daveman692"],
  ["urlToGraphNode", "http://friendfeed.com/daveman692?service=magnolia", "sgn://friendfeed.com/?ident=daveman692"],
  ["urlToGraphNode", "http://friendfeed.com/daveman692?service=pownce", "sgn://friendfeed.com/?ident=daveman692"],
  ["urlToGraphNode", "http://friendfeed.com/daveman692?service=twitter", "sgn://friendfeed.com/?ident=daveman692"],
  ["urlToGraphNode", "http://friendfeed.com/daveman692?service=upcoming", "sgn://friendfeed.com/?ident=daveman692"],
  ["urlFromGraphNode", "sgn://friendfeed.com/?ident=ade", "profile", "http://friendfeed.com/ade"],
  ["urlToGraphNode", "http://friendfeed.com/ade", "sgn://friendfeed.com/?ident=ade"],
  ["urlFromGraphNode", "sgn://friendfeed.com/?ident=ade", "atom", "http://friendfeed.com/ade?format=atom"],
  ["urlToGraphNode", "http://friendfeed.com/ade?format=atom", "sgn://friendfeed.com/?ident=ade"],
  ["urlToGraphNode", "http://www.google.de/reader/shared/12649763491721032377", "sgn://reader.google.com/?pk=12649763491721032377"],
  ["urlToGraphNode", "http://www.google.com/reader/shared/12649763491721032377", "sgn://reader.google.com/?pk=12649763491721032377"],
  ["urlToGraphNode", "http://www.google.com/reader/public/atom/user/12649763491721032377/state/com.google/broadcast", "sgn://reader.google.com/?pk=12649763491721032377"],
  ["urlFromGraphNode", "sgn://reader.google.com/?pk=12649763491721032377", "content", "http://www.google.com/reader/shared/12649763491721032377"],
  ["urlToGraphNode", "http://www.google.com/reader/shared/12649763491721032377", "sgn://reader.google.com/?pk=12649763491721032377"],
  ["urlFromGraphNode", "sgn://reader.google.com/?pk=12649763491721032377", "profile", "http://www.google.com/reader/shared/12649763491721032377"],
  ["urlToGraphNode", "http://www.google.com/reader/shared/12649763491721032377", "sgn://reader.google.com/?pk=12649763491721032377"],
  ["urlFromGraphNode", "sgn://reader.google.com/?pk=12649763491721032377", "atom", "http://www.google.com/reader/public/atom/user/12649763491721032377/state/com.google/broadcast"],
  ["urlToGraphNode", "http://www.google.com/reader/public/atom/user/12649763491721032377/state/com.google/broadcast", "sgn://reader.google.com/?pk=12649763491721032377"],
  ["urlToGraphNode", "http://youtube.com/jsmarr", "sgn://youtube.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://www.youtube.com/user/jsmarr", "sgn://youtube.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://www.youtube.com/profile?user=bradfitztube", "sgn://youtube.com/?ident=bradfitztube"],
  ["urlToGraphNode", "http://www.youtube.com/watch?v=pF20uyMTqqI", "http://www.youtube.com/watch?v=pF20uyMTqqI"],
  ["urlToGraphNode", "http://gdata.youtube.com/feeds/base/users/bradfitztube/uploads?alt=rss&v=2&client=ytapi-youtube-profile", "sgn://youtube.com/?ident=bradfitztube"],
  ["urlFromGraphNode", "sgn://youtube.com/?ident=jsmarr", "profile", "http://youtube.com/user/jsmarr"],
  ["urlToGraphNode", "http://youtube.com/user/jsmarr", "sgn://youtube.com/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://youtube.com/?ident=jsmarr", "rss", "http://youtube.com/rss/user/jsmarr/videos.rss"],
  ["urlToGraphNode", "http://youtube.com/rss/user/jsmarr/videos.rss", "sgn://youtube.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://www.dodgeball.com/user?uid=54155", "sgn://dodgeball.com/?pk=54155"],
  ["urlFromGraphNode", "sgn://dodgeball.com/?pk=54155", "profile", "http://www.dodgeball.com/user?uid=54155"],
  ["urlToGraphNode", "http://www.dodgeball.com/user?uid=54155", "sgn://dodgeball.com/?pk=54155"],
  ["urlToGraphNode", "http://picasaweb.google.com/bradley.j.fitzpatrick/", "sgn://picasaweb.google.com/?ident=bradley.j.fitzpatrick"],
  ["urlToGraphNode", "http://picasaweb.google.com/bradley.j.FITZPATRICK/", "sgn://picasaweb.google.com/?ident=bradley.j.fitzpatrick"],
  ["urlToGraphNode", "http://picasaweb.google.com/jsmarr", "sgn://picasaweb.google.com/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://picasaweb.google.com/?ident=jsmarr", "profile", "http://picasaweb.google.com/jsmarr"],
  ["urlToGraphNode", "http://picasaweb.google.com/jsmarr", "sgn://picasaweb.google.com/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://picasaweb.google.com/?ident=jsmarr", "rss", "http://picasaweb.google.com/data/feed/base/user/jsmarr?kind=album&alt=rss&hl=en_US&access=public"],
  ["urlToGraphNode", "http://picasaweb.google.com/data/feed/base/user/jsmarr?kind=album&alt=rss&hl=en_US&access=public", "sgn://picasaweb.google.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://www.orkut.com/Profile.aspx?uid=123", "sgn://orkut.com/?pk=123"],
  ["urlFromGraphNode", "sgn://orkut.com/?pk=123", "profile", "http://www.orkut.com/Profile.aspx?uid=123"],
  ["urlToGraphNode", "http://www.orkut.com/Profile.aspx?uid=123", "sgn://orkut.com/?pk=123"],
  ["urlToGraphNode", "http://picasaweb.google.es/Abc.Def", "sgn://picasaweb.google.com/?ident=abc.def"],
  ["urlToGraphNode", "http://picasaweb.google.hu/abcdef", "sgn://picasaweb.google.com/?ident=abcdef"],
  ["urlToGraphNode", "http://www.picasaweb.google.hu/abcdef", "sgn://picasaweb.google.com/?ident=abcdef"],
  ["urlToGraphNode", "http://www.google.com/s2/profiles/115863474911002159675", "sgn://profiles.google.com/?pk=115863474911002159675"],
  ["urlToGraphNode", "http://www.google.com/profiles/115863474911002159675", "sgn://profiles.google.com/?pk=115863474911002159675"],
  ["urlToGraphNode", "http://www.google.co.uk/s2/profiles/115863474911002159675", "sgn://profiles.google.com/?pk=115863474911002159675"],
  ["urlToGraphNode", "http://www.google.de/s2/profiles/115863474911002159675", "sgn://profiles.google.com/?pk=115863474911002159675"],
  ["urlToGraphNode", "http://www.google.com/profiles/bradfitz", "sgn://profiles.google.com/?ident=bradfitz"],
  ["urlToGraphNode", "http://profiles.google.com/bradfitz", "sgn://profiles.google.com/?ident=bradfitz"],
  ["urlToGraphNode", "http://profiles.google.com/bradfitz?foo", "sgn://profiles.google.com/?ident=bradfitz"],
  ["urlToGraphNode", "http://www.google.com/s2/sharing/stuff?user=123", "sgn://profiles.google.com/?pk=123"],
  ["urlFromGraphNode", "sgn://profiles.google.com/?pk=115863474911002159675", "profile", "http://www.google.com/profiles/115863474911002159675"],
  ["urlToGraphNode", "http://www.google.com/profiles/115863474911002159675", "sgn://profiles.google.com/?pk=115863474911002159675"],
  ["urlFromGraphNode", "sgn://profiles.google.com/?ident=bradfitz", "profile", "http://www.google.com/profiles/bradfitz"],
  ["urlToGraphNode", "http://www.google.com/profiles/bradfitz", "sgn://profiles.google.com/?ident=bradfitz"],
  ["urlToGraphNode", "http://api.hi5.com/rest/profile/foaf/87628233", "sgn://hi5.com/?pk=87628233"],
  ["urlToGraphNode", "http://lindner.hi5.com/", "sgn://hi5.com/?ident=lindner"],
  ["urlToGraphNode", "http://123455.hi5.com/", "sgn://hi5.com/?pk=123455"],
  ["urlToGraphNode", "http://www.hi5.com/", "http://www.hi5.com/"],
  ["urlToGraphNode", "http://api.hi5.com/", "http://api.hi5.com/"],
  ["urlToGraphNode", "http://www.hi5.com/friend/profile/displayProfile.do?userid=127525866", "sgn://hi5.com/?pk=127525866"],
  ["urlToGraphNode", "http://lindner.hi5.com/friend/profile/displayJournal.do?viewother=true&ownerId=87628233", "sgn://hi5.com/?pk=87628233"],
  ["urlToGraphNode", "http://lindner.hi5.com/friend/photos/displayUserAlbum.do?viewother=true&ownerId=87628233", "sgn://hi5.com/?pk=87628233"],
  ["urlToGraphNode", "http://bradfitz.hi5.com/friend/photos/displayUserAlbum.do?viewother=true&ownerId=87628233", "sgn://hi5.com/?pk=87628233"],
  ["urlToGraphNode", "http://lindner.hi5.com/friend/87628233--Paul--Profile-html", "sgn://hi5.com/?pk=87628233"],
  ["urlToGraphNode", "http://bradfitz.hi5.com/friend/87628233--Paul--Profile-html", "sgn://hi5.com/?pk=87628233"],
  ["urlToGraphNode", "http://lindner.hi5.com/friend/87628233--Paul--Friends-html", "sgn://hi5.com/?pk=87628233"],
  ["urlToGraphNode", "http://lindner.hi5.com/friend/profile/displayFriends.do?userid=87628233&offset=24", "sgn://hi5.com/?pk=87628233"],
  ["urlToGraphNode", "http://bradfitz.hi5.com/friend/87628233--Paul--Friends-html", "sgn://hi5.com/?pk=87628233"],
  ["urlToGraphNode", "http://lindner.hi5.com/friend/30399640--Dan--Profile-html", "sgn://hi5.com/?pk=30399640"],
  ["urlToGraphNode", "http://www.hi5.com/friend/profile/displaySameProfile.do?userid=87628233", "sgn://hi5.com/?pk=87628233"],
  ["urlToGraphNode", "http://www.hi5.com/friend/profile/displayHi5URL.do?nickname=koolby", "sgn://hi5.com/?ident=koolby"],
  ["urlToGraphNode", "http://www.hi5.com/friend/profile/displayHi5URL.do?nickname=bradfitz", "sgn://hi5.com/?ident=bradfitz"],
  ["urlFromGraphNode", "sgn://hi5.com/?pk=123", "content", "http://www.hi5.com/friend/profile/displayProfile.do?userid=123"],
  ["urlToGraphNode", "http://www.hi5.com/friend/profile/displayProfile.do?userid=123", "sgn://hi5.com/?pk=123"],
  ["urlFromGraphNode", "sgn://hi5.com/?pk=123", "profile", "http://www.hi5.com/friend/profile/displayProfile.do?userid=123"],
  ["urlToGraphNode", "http://www.hi5.com/friend/profile/displayProfile.do?userid=123", "sgn://hi5.com/?pk=123"],
  ["urlFromGraphNode", "sgn://hi5.com/?pk=123", "atom", "http://api.hi5.com/rest/feed/journal/123"],
  ["urlToGraphNode", "http://api.hi5.com/rest/feed/journal/123", "sgn://hi5.com/?pk=123"],
  ["urlFromGraphNode", "sgn://hi5.com/?pk=87628233", "foaf", "http://api.hi5.com/rest/profile/foaf/87628233"],
  ["urlToGraphNode", "http://api.hi5.com/rest/profile/foaf/87628233", "sgn://hi5.com/?pk=87628233"],
  ["urlFromGraphNode", "sgn://hi5.com/?pk=12345", "blog", "http://www.hi5.com/friend/profile/displayJournal.do?userid=12345"],
  ["urlToGraphNode", "http://www.hi5.com/friend/profile/displayJournal.do?userid=12345", "sgn://hi5.com/?pk=12345"],
  ["urlFromGraphNode", "sgn://hi5.com/?ident=bobfoo", "content", "http://bobfoo.hi5.com/"],
  ["urlToGraphNode", "http://bobfoo.hi5.com/", "sgn://hi5.com/?ident=bobfoo"],
  ["urlFromGraphNode", "sgn://hi5.com/?ident=bobfoo", "profile", "http://bobfoo.hi5.com/"],
  ["urlToGraphNode", "http://bobfoo.hi5.com/", "sgn://hi5.com/?ident=bobfoo"],
  ["urlToGraphNode", "http://53835694.hi5.com/friend/profile/displayProfile.do", "sgn://hi5.com/?pk=53835694"],
  ["urlToGraphNode", "http://bobfoo.hi5.com/friend/p1234--Foo_Bar%20Bar--html", "sgn://hi5.com/?pk=1234"],
  ["urlToGraphNode", "http://bobfoo.hi5.com/friend/p5678--Paula--html", "sgn://hi5.com/?pk=5678"],
  ["urlToGraphNode", "http://www.last.fm/user/aa123/", "sgn://last.fm/?ident=aa123"],
  ["urlToGraphNode", "http://www.last.fm/user/aa123", "sgn://last.fm/?ident=aa123"],
  ["urlToGraphNode", "http://lastfm.excite.co.jp/user/SomeCaps/", "sgn://last.fm/?ident=somecaps"],
  ["urlToGraphNode", "http://www.last.fm/user/after/addedevents/", "sgn://last.fm/?ident=after"],
  ["urlToGraphNode", "http://www.lastfm.pl/user/foo/?setlang=pl", "sgn://last.fm/?ident=foo"],
  ["urlToGraphNode", "http://www.lastfm.com.br/user/Steph-Tara/?setlang=tr", "sgn://last.fm/?ident=steph-tara"],
  ["urlToGraphNode", "http://www.lastfm.com.tr/user/Steph-Tara/charts/?setlang=tr", "sgn://last.fm/?ident=steph-tara"],
  ["urlToGraphNode", "http://cn.last.fm/user/Steph-Tara/neighbours/", "sgn://last.fm/?ident=steph-tara"],
  ["urlFromGraphNode", "sgn://last.fm/?ident=foo", "profile", "http://www.last.fm/user/foo/"],
  ["urlToGraphNode", "http://www.last.fm/user/foo/", "sgn://last.fm/?ident=foo"],
  ["urlToGraphNode", "http://brad.livejournal.com/", "sgn://livejournal.com/?ident=brad"],
  ["urlToGraphNode", "http://brad.livejournal.com/profile", "sgn://livejournal.com/?ident=brad"],
  ["urlToGraphNode", "http://brad.livejournal.com/data/foaf", "sgn://livejournal.com/?ident=brad"],
  ["urlToGraphNode", "http://brad.livejournal.com/data/rss", "sgn://livejournal.com/?ident=brad"],
  ["urlToGraphNode", "http://brad.livejournal.com/data/atom", "sgn://livejournal.com/?ident=brad"],
  ["urlFromGraphNode", "sgn://livejournal.com/?ident=brad", "content", "http://brad.livejournal.com/"],
  ["urlToGraphNode", "http://brad.livejournal.com/", "sgn://livejournal.com/?ident=brad"],
  ["urlToGraphNode", "http://a-b.livejournal.com/", "sgn://livejournal.com/?ident=a_b"],
  ["urlToGraphNode", "http://a-b.livejournal.com/profile", "sgn://livejournal.com/?ident=a_b"],
  ["urlFromGraphNode", "sgn://livejournal.com/?ident=a_b", "content", "http://a-b.livejournal.com/"],
  ["urlToGraphNode", "http://a-b.livejournal.com/", "sgn://livejournal.com/?ident=a_b"],
  ["urlFromGraphNode", "sgn://livejournal.com/?ident=_underscores_", "content", "http://www.livejournal.com/~_underscores_/"],
  ["urlToGraphNode", "http://www.livejournal.com/~_underscores_/", "sgn://livejournal.com/?ident=_underscores_"],
  ["urlToGraphNode", "http://users.livejournal.com/_underscores_/", "sgn://livejournal.com/?ident=_underscores_"],
  ["urlToGraphNode", "http://users.livejournal.com/_underscores_/profile", "sgn://livejournal.com/?ident=_underscores_"],
  ["urlToGraphNode", "http://users.livejournal.com/_underscores_", "sgn://livejournal.com/?ident=_underscores_"],
  ["urlToGraphNode", "http://users.livejournal.com/_u_/profile", "sgn://livejournal.com/?ident=_u_"],
  ["urlToGraphNode", "http://community.livejournal.com/linux/profile", "sgn://livejournal.com/?ident=linux"],
  ["urlToGraphNode", "http://community.livejournal.com/linux/", "sgn://livejournal.com/?ident=linux"],
  ["urlToGraphNode", "http://community.livejournal.com/linux", "sgn://livejournal.com/?ident=linux"],
  ["urlToGraphNode", "http://www.livejournal.com/~abc/", "sgn://livejournal.com/?ident=abc"],
  ["urlToGraphNode", "http://www.livejournal.com/~abc", "sgn://livejournal.com/?ident=abc"],
  ["urlToGraphNode", "http://livejournal.com/~abc/", "sgn://livejournal.com/?ident=abc"],
  ["urlToGraphNode", "http://livejournal.com/~abc", "sgn://livejournal.com/?ident=abc"],
  ["urlToGraphNode", "http://livejournal.com/users/bob", "sgn://livejournal.com/?ident=bob"],
  ["urlToGraphNode", "http://livejournal.com/users/bob/", "sgn://livejournal.com/?ident=bob"],
  ["urlFromGraphNode", "sgn://livejournal.com/?ident=abc", "rss", "http://abc.livejournal.com/data/rss"],
  ["urlToGraphNode", "http://abc.livejournal.com/data/rss", "sgn://livejournal.com/?ident=abc"],
  ["urlFromGraphNode", "sgn://livejournal.com/?ident=abc", "atom", "http://abc.livejournal.com/data/atom"],
  ["urlToGraphNode", "http://abc.livejournal.com/data/atom", "sgn://livejournal.com/?ident=abc"],
  ["urlFromGraphNode", "sgn://livejournal.com/?ident=abc", "foaf", "http://abc.livejournal.com/data/foaf"],
  ["urlToGraphNode", "http://abc.livejournal.com/data/foaf", "sgn://livejournal.com/?ident=abc"],
  ["urlFromGraphNode", "sgn://livejournal.com/?ident=abc", "openid", "http://abc.livejournal.com/"],
  ["urlToGraphNode", "http://abc.livejournal.com/", "sgn://livejournal.com/?ident=abc"],
  ["urlFromGraphNode", "sgn://livejournal.com/?ident=abc", "openid", "http://abc.livejournal.com/"],
  ["urlToGraphNode", "http://abc.livejournal.com/", "sgn://livejournal.com/?ident=abc"],
  ["urlToGraphNode", "http://www.livejournal.com/userinfo.bml?userid=123&t=I", "sgn://livejournal.com/?pk=123"],
  ["urlToGraphNode", "http://www.livejournal.com/userinfo.bml?userid=123", "sgn://livejournal.com/?pk=123"],
  ["urlToGraphNode", "http://www.livejournal.com/userinfo.bml?user=bob", "sgn://livejournal.com/?ident=bob"],
  ["urlToGraphNode", "http://www.livejournal.com/userinfo.bml?user=Bob&mode=full", "sgn://livejournal.com/?ident=bob"],
  ["urlFromGraphNode", "sgn://livejournal.com/?ident=bob", "profile", "http://bob.livejournal.com/profile"],
  ["urlToGraphNode", "http://bob.livejournal.com/profile", "sgn://livejournal.com/?ident=bob"],
  ["urlToGraphNode", "http://www.livejournal.com/go.bml?journal=bob&itemid=1929138&dir=next", "sgn://livejournal.com/?ident=bob"],
  ["urlToGraphNode", "http://www.livejournal.com/go.bml?journal=bob&itemid=1929138&dir=prev", "sgn://livejournal.com/?ident=bob"],
  ["urlToGraphNode", "http://www.livejournal.com/talkread.bml?journal=bob&itemid=1724560", "sgn://livejournal.com/?ident=bob"],
  ["urlToGraphNode", "http://pics.livejournal.com/brad/pic/0000g163/g4", "sgn://livejournal.com/?ident=brad"],
  ["urlToGraphNode", "http://pics.livejournal.com/", "http://pics.livejournal.com/"],
  ["urlToGraphNode", "http://www.livejournal.com/misc/fdata.bml?user=brad", "sgn://livejournal.com/?ident=brad"],
  ["urlToGraphNode", "http://www.livejournal.com/misc/fdata2.bml?user=brad", "sgn://livejournal.com/?ident=brad"],
  ["urlToGraphNode", "http://www.meetup.com/members/2949792/", "sgn://meetup.com/?pk=2949792"],
  ["urlToGraphNode", "http://coffee.meetup.com/171/members/2949792/?gj=sj3", "sgn://meetup.com/?pk=2949792"],
  ["urlToGraphNode", "http://coffee.meetup.com/171/members/2949792/", "sgn://meetup.com/?pk=2949792"],
  ["urlToGraphNode", "http://www.meetup.com/members/65", "sgn://meetup.com/?pk=65"],
  ["urlToGraphNode", "http://www.meetup.com/members/65/", "sgn://meetup.com/?pk=65"],
  ["urlToGraphNode", "http://MEETup.com/members/65", "sgn://meetup.com/?pk=65"],
  ["urlToGraphNode", "http://meetup.com/members/65/", "sgn://meetup.com/?pk=65"],
  ["urlFromGraphNode", "sgn://meetup.com/?pk=65", "profile", "http://www.meetup.com/members/65/"],
  ["urlToGraphNode", "http://www.meetup.com/members/65/", "sgn://meetup.com/?pk=65"],
  ["urlToGraphNode", "http://www.mybloglog.com/buzz/members/1143al", "sgn://mybloglog.com/?ident=1143al"],
  ["urlToGraphNode", "http://www.mybloglog.com/buzz/members/1143AL", "sgn://mybloglog.com/?ident=1143al"],
  ["urlToGraphNode", "http://www.mybloglog.com/buzz/members/1143AL/", "sgn://mybloglog.com/?ident=1143al"],
  ["urlToGraphNode", "http://mybloglog.com/buzz/members/1143AL/", "sgn://mybloglog.com/?ident=1143al"],
  ["urlToGraphNode", "http://www.mybloglog.com/buzz/members/HERBERT/", "sgn://mybloglog.com/?ident=herbert"],
  ["urlFromGraphNode", "sgn://mybloglog.com/?ident=herbert", "foaf", "http://www.mybloglog.com/buzz/members/herbert/foaf"],
  ["urlToGraphNode", "http://www.mybloglog.com/buzz/members/herbert/foaf", "sgn://mybloglog.com/?ident=herbert"],
  ["urlFromGraphNode", "sgn://mybloglog.com/?ident=herbert", "profile", "http://www.mybloglog.com/buzz/members/herbert/"],
  ["urlToGraphNode", "http://www.mybloglog.com/buzz/members/herbert/", "sgn://mybloglog.com/?ident=herbert"],
  ["urlToGraphNode", "http://www.mybloglog.com/buzz/members/mybloglog97cb9f03ecc30acfa597/", "sgn://mybloglog.com/?pk=97cb9f03ecc30acfa597"],
  ["urlFromGraphNode", "sgn://mybloglog.com/?pk=97cb9f03ecc30acfa597", "foaf", "http://www.mybloglog.com/buzz/members/mybloglog97cb9f03ecc30acfa597/foaf"],
  ["urlToGraphNode", "http://www.mybloglog.com/buzz/members/mybloglog97cb9f03ecc30acfa597/foaf", "sgn://mybloglog.com/?pk=97cb9f03ecc30acfa597"],
  ["urlFromGraphNode", "sgn://mybloglog.com/?pk=97cb9f03ecc30acfa597", "profile", "http://www.mybloglog.com/buzz/members/mybloglog97cb9f03ecc30acfa597/"],
  ["urlToGraphNode", "http://www.mybloglog.com/buzz/members/mybloglog97cb9f03ecc30acfa597/", "sgn://mybloglog.com/?pk=97cb9f03ecc30acfa597"],
  ["urlToGraphNode", "http://myspace.com/foobar", "sgn://myspace.com/?ident=foobar"],
  ["urlToGraphNode", "http://www.myspace.com/foobar", "sgn://myspace.com/?ident=foobar"],
  ["urlToGraphNode", "http://myspace.com/foobar/", "sgn://myspace.com/?ident=foobar"],
  ["urlToGraphNode", "http://profile.myspace.com/37715961", "sgn://myspace.com/?pk=37715961"],
  ["urlToGraphNode", "http://profile.myspace.com/uhhhh_freakin_idiot", "sgn://myspace.com/?ident=uhhhh_freakin_idiot"],
  ["urlToGraphNode", "http://profile.myspace.com/k93", "sgn://myspace.com/?ident=k93"],
  ["urlToGraphNode", "http://www.myspace.com/index.cfm?fuseaction=user.viewprofile&friendid=73394553", "sgn://myspace.com/?pk=73394553"],
  ["urlToGraphNode", "http://profile.myspace.com/index.cfm?fuseaction=user.viewprofile&friendid=73394553", "sgn://myspace.com/?pk=73394553"],
  ["urlToGraphNode", "http://blog.myspace.com/index.cfm?fuseaction=blog.ListAll&friendID=64410858", "sgn://myspace.com/?pk=64410858"],
  ["urlToGraphNode", "http://blog.myspace.com/index.cfm?fuseaction=blog.ConfirmSubscribe&friendID=64410858", "sgn://myspace.com/?pk=64410858"],
  ["urlToGraphNode", "http://profile.myspace.com/index.cfm?fuseaction=user.viewProfile&friendID=34718576", "sgn://myspace.com/?pk=34718576"],
  ["urlToGraphNode", "http://friends.myspace.com/index.cfm?fuseaction=user.viewfriends&friendID=64410858", "sgn://myspace.com/?pk=64410858"],
  ["urlFromGraphNode", "sgn://myspace.com/?pk=123", "profile", "http://profile.myspace.com/index.cfm?fuseaction=user.viewprofile&friendid=123"],
  ["urlToGraphNode", "http://profile.myspace.com/index.cfm?fuseaction=user.viewprofile&friendid=123", "sgn://myspace.com/?pk=123"],
  ["urlFromGraphNode", "sgn://myspace.com/?pk=123", "blog", "http://blog.myspace.com/index.cfm?fuseaction=blog.ListAll&friendID=123"],
  ["urlToGraphNode", "http://blog.myspace.com/index.cfm?fuseaction=blog.ListAll&friendID=123", "sgn://myspace.com/?pk=123"],
  ["urlFromGraphNode", "sgn://myspace.com/?pk=123", "rss", "http://blog.myspace.com/blog/rss.cfm?friendID=123"],
  ["urlToGraphNode", "http://blog.myspace.com/blog/rss.cfm?friendID=123", "sgn://myspace.com/?pk=123"],
  ["urlFromGraphNode", "sgn://myspace.com/?ident=foobar", "profile", "http://www.myspace.com/foobar"],
  ["urlToGraphNode", "http://www.myspace.com/foobar", "sgn://myspace.com/?ident=foobar"],
  ["urlFromGraphNode", "sgn://myspace.com/?ident=foobar", "content", "http://www.myspace.com/foobar"],
  ["urlToGraphNode", "http://www.myspace.com/foobar", "sgn://myspace.com/?ident=foobar"],
  ["urlToGraphNode", "xmpp:foo%40bar.com", "xmpp:foo@bar.com"],
  ["urlToGraphNode", "jabber:foo%40bar.com", "xmpp:foo@bar.com"],
  ["urlToGraphNode", "Xmpp:foo@bar.com", "xmpp:foo@bar.com"],
  ["urlToGraphNode", "jabber:foo@bar.com", "xmpp:foo@bar.com"],
  ["urlToGraphNode", "Mailto:brad%40bar.com", "mailto:brad@bar.com"],
  ["urlToGraphNode", "http://my.opera.com/jsmarr", "sgn://my.opera.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://my.opera.com/jsmarr/", "sgn://my.opera.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://my.opera.com/jSMArr/", "sgn://my.opera.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://my.opera.com/jsmarr/about", "sgn://my.opera.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://my.opera.com/jsmarr/info/", "sgn://my.opera.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://my.opera.com/jsmarr/xml/foaf/", "sgn://my.opera.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://my.opera.com/1966/xml/foaf/", "sgn://my.opera.com/?ident=1966"],
  ["urlFromGraphNode", "sgn://my.opera.com/?ident=jsmarr", "profile", "http://my.opera.com/jsmarr/about/"],
  ["urlToGraphNode", "http://my.opera.com/jsmarr/about/", "sgn://my.opera.com/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://my.opera.com/?ident=1966", "profile", "http://my.opera.com/1966/about/"],
  ["urlToGraphNode", "http://my.opera.com/1966/about/", "sgn://my.opera.com/?ident=1966"],
  ["urlFromGraphNode", "sgn://my.opera.com/?ident=jsmarr", "foaf", "http://my.opera.com/jsmarr/xml/foaf/"],
  ["urlToGraphNode", "http://my.opera.com/jsmarr/xml/foaf/", "sgn://my.opera.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://my.opera.com/%3EFoo/", "sgn://my.opera.com/?ident=%3efoo"],
  ["urlToGraphNode", "http://my.opera.com/.:Foo%20Bar:./", "sgn://my.opera.com/?ident=.:foo%20bar:."],
  ["urlToGraphNode", "http://my.opera.com/Milla***/xml/foaf", "sgn://my.opera.com/?ident=milla***"],
  ["urlToGraphNode", "http://my.opera.com/Molly-Jayne/xml/foaf", "sgn://my.opera.com/?ident=molly-jayne"],
  ["urlFromGraphNode", "sgn://my.opera.com/?ident=molly-jayne", "foaf", "http://my.opera.com/molly-jayne/xml/foaf/"],
  ["urlToGraphNode", "http://my.opera.com/molly-jayne/xml/foaf/", "sgn://my.opera.com/?ident=molly-jayne"],
  ["urlToGraphNode", "http://allatigris.gallery.ru/", "sgn://gallery.ru/?ident=allatigris"],
  ["urlToGraphNode", "http://allatigris.gallery.ru/foaf/", "sgn://gallery.ru/?ident=allatigris"],
  ["urlToGraphNode", "http://allatigris.gallery.ru/?favs=1", "sgn://gallery.ru/?ident=allatigris"],
  ["urlFromGraphNode", "sgn://gallery.ru/?ident=allatigris", "foaf", "http://allatigris.gallery.ru/foaf/"],
  ["urlToGraphNode", "http://allatigris.gallery.ru/foaf/", "sgn://gallery.ru/?ident=allatigris"],
  ["urlFromGraphNode", "sgn://gallery.ru/?ident=allatigris", "profile", "http://allatigris.gallery.ru/"],
  ["urlToGraphNode", "http://allatigris.gallery.ru/", "sgn://gallery.ru/?ident=allatigris"],
  ["urlToGraphNode", "http://www.blogonline.ru/", "http://www.blogonline.ru/"],
  ["urlToGraphNode", "http://allis.blogonline.ru/", "sgn://blogonline.ru/?ident=allis"],
  ["urlFromGraphNode", "sgn://blogonline.ru/?ident=allis", "foaf", "http://allis.blogonline.ru/data/foaf"],
  ["urlToGraphNode", "http://allis.blogonline.ru/data/foaf", "sgn://blogonline.ru/?ident=allis"],
  ["urlFromGraphNode", "sgn://blogonline.ru/?ident=allis", "profile", "http://allis.blogonline.ru/profile"],
  ["urlToGraphNode", "http://allis.blogonline.ru/profile", "sgn://blogonline.ru/?ident=allis"],
  ["urlFromGraphNode", "sgn://blogonline.ru/?ident=allis", "blog", "http://allis.blogonline.ru/"],
  ["urlToGraphNode", "http://allis.blogonline.ru/", "sgn://blogonline.ru/?ident=allis"],
  ["urlFromGraphNode", "sgn://privet.ru/?ident=aleksina_647", "foaf", "http://www.privet.ru/user/aleksina_647/foaf"],
  ["urlToGraphNode", "http://www.privet.ru/user/aleksina_647/foaf", "sgn://privet.ru/?ident=aleksina_647"],
  ["urlFromGraphNode", "sgn://privet.ru/?ident=aleksina_647", "blog", "http://blogs.privet.ru/user/aleksina_647"],
  ["urlToGraphNode", "http://blogs.privet.ru/user/aleksina_647", "sgn://privet.ru/?ident=aleksina_647"],
  ["urlFromGraphNode", "sgn://privet.ru/?ident=aleksina_647", "profile", "http://www.privet.ru/user/aleksina_647"],
  ["urlToGraphNode", "http://www.privet.ru/user/aleksina_647", "sgn://privet.ru/?ident=aleksina_647"],
  ["urlToGraphNode", "http://cibertulia.blogs.sapo.pt/1278408.html", "sgn://blogs.sapo.pt/?ident=cibertulia"],
  ["urlFromGraphNode", "sgn://blogs.sapo.pt/?ident=cibertulia", "foaf", "http://cibertulia.blogs.sapo.pt/data/foaf"],
  ["urlToGraphNode", "http://cibertulia.blogs.sapo.pt/data/foaf", "sgn://blogs.sapo.pt/?ident=cibertulia"],
  ["urlFromGraphNode", "sgn://blogs.sapo.pt/?ident=cibertulia", "blog", "http://cibertulia.blogs.sapo.pt/"],
  ["urlToGraphNode", "http://cibertulia.blogs.sapo.pt/", "sgn://blogs.sapo.pt/?ident=cibertulia"],
  ["urlToGraphNode", "http://digg.com/users/foobar", "sgn://digg.com/?ident=foobar"],
  ["urlToGraphNode", "http://digg.com/users/foobar/", "sgn://digg.com/?ident=foobar"],
  ["urlToGraphNode", "http://digg.com/users/foobar/history/diggs.rss", "sgn://digg.com/?ident=foobar"],
  ["urlToGraphNode", "http://digg.com/rss/foobar/index2.xml", "sgn://digg.com/?ident=foobar"],
  ["urlFromGraphNode", "sgn://digg.com/?ident=foobar", "profile", "http://digg.com/users/foobar/"],
  ["urlToGraphNode", "http://digg.com/users/foobar/", "sgn://digg.com/?ident=foobar"],
  ["urlFromGraphNode", "sgn://digg.com/?ident=foobar", "rss", "http://digg.com/users/foobar/history/diggs.rss"],
  ["urlToGraphNode", "http://digg.com/users/foobar/history/diggs.rss", "sgn://digg.com/?ident=foobar"],
  ["urlToGraphNode", "http://pownce.com/a", "sgn://pownce.com/?ident=a"],
  ["urlToGraphNode", "http://pownce.com/A", "sgn://pownce.com/?ident=a"],
  ["urlToGraphNode", "http://pownce.com/A/", "sgn://pownce.com/?ident=a"],
  ["urlToGraphNode", "http://pownce.com/A/public/", "sgn://pownce.com/?ident=a"],
  ["urlToGraphNode", "http://pownce.com/A/public/with_friends", "sgn://pownce.com/?ident=a"],
  ["urlToGraphNode", "http://pownce.com/bob/foaf/", "sgn://pownce.com/?ident=bob"],
  ["urlFromGraphNode", "sgn://pownce.com/?ident=a", "profile", "http://pownce.com/a"],
  ["urlToGraphNode", "http://pownce.com/a", "sgn://pownce.com/?ident=a"],
  ["urlFromGraphNode", "sgn://pownce.com/?ident=a", "rss", "http://pownce.com/feeds/public/a.rss"],
  ["urlToGraphNode", "http://pownce.com/feeds/public/a.rss", "sgn://pownce.com/?ident=a"],
  ["urlFromGraphNode", "sgn://pownce.com/?ident=a", "atom", "http://pownce.com/feeds/public/a.atom"],
  ["urlToGraphNode", "http://pownce.com/feeds/public/a.atom", "sgn://pownce.com/?ident=a"],
  ["urlToGraphNode", "http://bradfitz.jaiku.com/", "sgn://jaiku.com/?ident=bradfitz"],
  ["urlToGraphNode", "http://BRADFITZ.JAIKU.COM/", "sgn://jaiku.com/?ident=bradfitz"],
  ["urlFromGraphNode", "sgn://jaiku.com/?ident=bradfitz", "profile", "http://bradfitz.jaiku.com/"],
  ["urlToGraphNode", "http://bradfitz.jaiku.com/", "sgn://jaiku.com/?ident=bradfitz"],
  ["urlFromGraphNode", "sgn://jaiku.com/?ident=bradfitz", "rss", "http://bradfitz.jaiku.com/feed/rss"],
  ["urlToGraphNode", "http://bradfitz.jaiku.com/feed/rss", "sgn://jaiku.com/?ident=bradfitz"],
  ["urlToGraphNode", "http://linkedin.com/in/foobar", "sgn://linkedin.com/?ident=foobar"],
  ["urlToGraphNode", "http://linkedin.com/in/foobar/", "sgn://linkedin.com/?ident=foobar"],
  ["urlToGraphNode", "http://www.linkedin.com/in/foobar/", "sgn://linkedin.com/?ident=foobar"],
  ["urlToGraphNode", "http://www.linkedin.com/in/foobar", "sgn://linkedin.com/?ident=foobar"],
  ["urlFromGraphNode", "sgn://linkedin.com/?ident=foobar", "profile", "http://www.linkedin.com/in/foobar"],
  ["urlToGraphNode", "http://www.linkedin.com/in/foobar", "sgn://linkedin.com/?ident=foobar"],
  ["urlToGraphNode", "http://ma.gnolia.com/people/daveman692", "sgn://ma.gnolia.com/?ident=daveman692"],
  ["urlToGraphNode", "http://ma.gnolia.com/people/daveman692/", "sgn://ma.gnolia.com/?ident=daveman692"],
  ["urlFromGraphNode", "sgn://ma.gnolia.com/?ident=daveman692", "profile", "http://ma.gnolia.com/people/daveman692"],
  ["urlToGraphNode", "http://ma.gnolia.com/people/daveman692", "sgn://ma.gnolia.com/?ident=daveman692"],
  ["urlFromGraphNode", "sgn://ma.gnolia.com/?ident=daveman692", "rss", "http://ma.gnolia.com/rss/full/people/daveman692"],
  ["urlToGraphNode", "http://ma.gnolia.com/rss/full/people/daveman692", "sgn://ma.gnolia.com/?ident=daveman692"],
  ["urlToGraphNode", "http://mugshot.org/person?who=7ACcH9gn7zv4YG", "sgn://mugshot.org/?ident=7ACcH9gn7zv4YG"],
  ["urlFromGraphNode", "sgn://mugshot.org/?ident=7ACcH9gn7zv4YG", "profile", "http://mugshot.org/person?who=7ACcH9gn7zv4YG"],
  ["urlToGraphNode", "http://mugshot.org/person?who=7ACcH9gn7zv4YG", "sgn://mugshot.org/?ident=7ACcH9gn7zv4YG"],
  ["urlToGraphNode", "http://www.ziki.com/en/people/bob", "sgn://ziki.com/?ident=bob"],
  ["urlToGraphNode", "http://www.ziki.com/fr/people/bob/", "sgn://ziki.com/?ident=bob"],
  ["urlToGraphNode", "http://www.ziki.com/fr/people/bob/extrastuff", "sgn://ziki.com/?ident=bob"],
  ["urlFromGraphNode", "sgn://ziki.com/?ident=bob", "profile", "http://www.ziki.com/people/bob"],
  ["urlToGraphNode", "http://www.ziki.com/people/bob", "sgn://ziki.com/?ident=bob"],
  ["urlToGraphNode", "http://del.icio.us/jsmarr", "sgn://del.icio.us/?ident=jsmarr"],
  ["urlToGraphNode", "http://del.icio.us/rss/jsmarr", "sgn://del.icio.us/?ident=jsmarr"],
  ["urlToGraphNode", "http://delicious.com/jsmarr", "sgn://del.icio.us/?ident=jsmarr"],
  ["urlToGraphNode", "http://delicious.com/rss/jsmarr", "sgn://del.icio.us/?ident=jsmarr"],
  ["urlToGraphNode", "http://feeds.delicious.com/rss/jsmarr", "sgn://del.icio.us/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://del.icio.us/?ident=jsmarr", "profile", "http://delicious.com/jsmarr"],
  ["urlToGraphNode", "http://delicious.com/jsmarr", "sgn://del.icio.us/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://del.icio.us/?ident=jsmarr", "rss", "http://feeds.delicious.com/rss/jsmarr"],
  ["urlToGraphNode", "http://feeds.delicious.com/rss/jsmarr", "sgn://del.icio.us/?ident=jsmarr"],
  ["urlToGraphNode", "http://community.webshots.com/user/bob", "sgn://webshots.com/?ident=bob"],
  ["urlFromGraphNode", "sgn://webshots.com/?ident=bob", "profile", "http://community.webshots.com/user/bob"],
  ["urlToGraphNode", "http://community.webshots.com/user/bob", "sgn://webshots.com/?ident=bob"],
  ["urlFromGraphNode", "sgn://webshots.com/?ident=bob", "rss", "http://community.webshots.com/rss?contentType=rss&type=user&value=bob"],
  ["urlToGraphNode", "http://community.webshots.com/rss?contentType=rss&type=user&value=bob", "sgn://webshots.com/?ident=bob"],
  ["urlToGraphNode", "http://jsmarr.smugmug.com", "sgn://smugmug.com/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://smugmug.com/?ident=jsmarr", "profile", "http://jsmarr.smugmug.com/"],
  ["urlToGraphNode", "http://jsmarr.smugmug.com/", "sgn://smugmug.com/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://smugmug.com/?ident=jsmarr", "atom", "http://www.smugmug.com/hack/feed.mg?Type=nicknameRecentPhotos&Data=jsmarr&format=atom03"],
  ["urlToGraphNode", "http://www.smugmug.com/hack/feed.mg?Type=nicknameRecentPhotos&Data=jsmarr&format=atom03", "sgn://smugmug.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://bradfitz.tumblr.com/", "sgn://tumblr.com/?ident=bradfitz"],
  ["urlFromGraphNode", "sgn://tumblr.com/?ident=bradfitz", "profile", "http://bradfitz.tumblr.com/"],
  ["urlToGraphNode", "http://bradfitz.tumblr.com/", "sgn://tumblr.com/?ident=bradfitz"],
  ["urlFromGraphNode", "sgn://tumblr.com/?ident=bradfitz", "rss", "http://bradfitz.tumblr.com/rss"],
  ["urlToGraphNode", "http://bradfitz.tumblr.com/rss", "sgn://tumblr.com/?ident=bradfitz"],
  ["urlToGraphNode", "http://xanga.com/a/", "sgn://xanga.com/?ident=a"],
  ["urlFromGraphNode", "sgn://xanga.com/?ident=a", "profile", "http://xanga.com/a"],
  ["urlToGraphNode", "http://xanga.com/a", "sgn://xanga.com/?ident=a"],
  ["urlFromGraphNode", "sgn://xanga.com/?ident=a", "rss", "http://xanga.com/a/rss"],
  ["urlToGraphNode", "http://xanga.com/a/rss", "sgn://xanga.com/?ident=a"],
  ["urlToGraphNode", "http://360.yahoo.com/a/", "sgn://360.yahoo.com/?ident=a"],
  ["urlFromGraphNode", "sgn://360.yahoo.com/?ident=a", "profile", "http://360.yahoo.com/a"],
  ["urlToGraphNode", "http://360.yahoo.com/a", "sgn://360.yahoo.com/?ident=a"],
  ["urlFromGraphNode", "sgn://360.yahoo.com/?ident=a", "rss", "http://blog.360.yahoo.com/a"],
  ["urlToGraphNode", "http://blog.360.yahoo.com/a", "sgn://360.yahoo.com/?ident=a"],
  ["urlToGraphNode", "http://bradfitz.spaces.live.com/", "sgn://spaces.live.com/?ident=bradfitz"],
  ["urlFromGraphNode", "sgn://spaces.live.com/?ident=bradfitz", "profile", "http://bradfitz.spaces.live.com"],
  ["urlToGraphNode", "http://bradfitz.spaces.live.com", "sgn://spaces.live.com/?ident=bradfitz"],
  ["urlFromGraphNode", "sgn://spaces.live.com/?ident=bradfitz", "rss", "http://bradfitz.spaces.live.com/feed.rss"],
  ["urlToGraphNode", "http://bradfitz.spaces.live.com/feed.rss", "sgn://spaces.live.com/?ident=bradfitz"],
  ["urlToGraphNode", "http://www.travelpod.com/members/foobar", "sgn://travelpod.com/?ident=foobar"],
  ["urlToGraphNode", "http://travelpod.com/members/foobar/", "sgn://travelpod.com/?ident=foobar"],
  ["urlFromGraphNode", "sgn://travelpod.com/?ident=foobar", "profile", "http://travelpod.com/members/foobar"],
  ["urlToGraphNode", "http://travelpod.com/members/foobar", "sgn://travelpod.com/?ident=foobar"],
  ["urlFromGraphNode", "sgn://travelpod.com/?ident=foobar", "rss", "http://travelpod.com/syndication/rss/foobar"],
  ["urlToGraphNode", "http://travelpod.com/syndication/rss/foobar", "sgn://travelpod.com/?ident=foobar"],
  ["urlToGraphNode", "http://www.imageshack.us/user/foobar", "sgn://imageshack.us/?ident=foobar"],
  ["urlToGraphNode", "http://imageshack.us/user/foobar/", "sgn://imageshack.us/?ident=foobar"],
  ["urlFromGraphNode", "sgn://imageshack.us/?ident=foobar", "profile", "http://profile.imageshack.us/user/foobar"],
  ["urlToGraphNode", "http://profile.imageshack.us/user/foobar", "sgn://imageshack.us/?ident=foobar"],
  ["urlFromGraphNode", "sgn://imageshack.us/?ident=foobar", "rss", "http://rss.imageshack.us/user/foobar/rss/"],
  ["urlToGraphNode", "http://rss.imageshack.us/user/foobar/rss/", "sgn://imageshack.us/?ident=foobar"],
  ["urlToGraphNode", "http://www.bloglines.com/blog/jsmarr", "sgn://bloglines.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://www.bloglines.com/blog/jsmarr/rss", "sgn://bloglines.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://www.bloglines.com/public/jsmarr", "sgn://bloglines.com/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://bloglines.com/?ident=jsmarr", "profile", "http://www.bloglines.com/blog/jsmarr"],
  ["urlToGraphNode", "http://www.bloglines.com/blog/jsmarr", "sgn://bloglines.com/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://bloglines.com/?ident=jsmarr", "rss", "http://www.bloglines.com/blog/jsmarr/rss"],
  ["urlToGraphNode", "http://www.bloglines.com/blog/jsmarr/rss", "sgn://bloglines.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://upcoming.yahoo.com/user/75587/", "sgn://upcoming.yahoo.com/?pk=75587"],
  ["urlToGraphNode", "http://upcoming.org/user/75587/", "sgn://upcoming.yahoo.com/?pk=75587"],
  ["urlFromGraphNode", "sgn://upcoming.yahoo.com/?pk=75587", "profile", "http://upcoming.yahoo.com/user/75587/"],
  ["urlToGraphNode", "http://upcoming.yahoo.com/user/75587/", "sgn://upcoming.yahoo.com/?pk=75587"],
  ["urlFromGraphNode", "sgn://upcoming.yahoo.com/?pk=75587", "rss", "http://upcoming.yahoo.com/syndicate/v2/my_events/75587"],
  ["urlToGraphNode", "http://upcoming.yahoo.com/syndicate/v2/my_events/75587", "sgn://upcoming.yahoo.com/?pk=75587"],
  ["urlToGraphNode", "http://timespeople.nytimes.com/view/user/57047872", "sgn://nytimes.com/?pk=57047872"],
  ["urlToGraphNode", "http://timespeople.nytimes.com/view/user/57047872/activities.html", "sgn://nytimes.com/?pk=57047872"],
  ["urlToGraphNode", "http://timespeople.nytimes.com/view/user/57047872/rss.xml", "sgn://nytimes.com/?pk=57047872"],
  ["urlFromGraphNode", "sgn://nytimes.com/?pk=57047872", "profile", "http://timespeople.nytimes.com/view/user/57047872/activities.html"],
  ["urlToGraphNode", "http://timespeople.nytimes.com/view/user/57047872/activities.html", "sgn://nytimes.com/?pk=57047872"],
  ["urlFromGraphNode", "sgn://nytimes.com/?pk=57047872", "rss", "http://timespeople.nytimes.com/view/user/57047872/rss.xml"],
  ["urlToGraphNode", "http://timespeople.nytimes.com/view/user/57047872/rss.xml", "sgn://nytimes.com/?pk=57047872"],
  ["urlToGraphNode", "http://www.socializr.com/user/jsmarr", "sgn://socializr.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://www.socializr.com/rss/user/jsmarr/rss.xml", "sgn://socializr.com/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://socializr.com/?ident=jsmarr", "profile", "http://www.socializr.com/user/jsmarr"],
  ["urlToGraphNode", "http://www.socializr.com/user/jsmarr", "sgn://socializr.com/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://socializr.com/?ident=jsmarr", "rss", "http://www.socializr.com/rss/user/jsmarr/rss.xml"],
  ["urlToGraphNode", "http://www.socializr.com/rss/user/jsmarr/rss.xml", "sgn://socializr.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://www.socializr.com/user/12345", "sgn://socializr.com/?pk=12345"],
  ["urlFromGraphNode", "sgn://socializr.com/?pk=12345", "profile", "http://www.socializr.com/user/12345"],
  ["urlToGraphNode", "http://www.socializr.com/user/12345", "sgn://socializr.com/?pk=12345"],
  ["urlFromGraphNode", "sgn://socializr.com/?pk=12345", "rss", "http://www.socializr.com/rss/user/12345/rss.xml"],
  ["urlToGraphNode", "http://www.socializr.com/rss/user/12345/rss.xml", "sgn://socializr.com/?pk=12345"],
  ["urlToGraphNode", "http://bebo.com/jsmarr", "sgn://bebo.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://bebo.com/Profile.jsp?MemberId=12345", "sgn://bebo.com/?pk=12345"],
  ["urlFromGraphNode", "sgn://bebo.com/?ident=jsmarr", "profile", "http://bebo.com/jsmarr"],
  ["urlToGraphNode", "http://bebo.com/jsmarr", "sgn://bebo.com/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://bebo.com/?pk=12345", "profile", "http://bebo.com/Profile.jsp?MemberId=12345"],
  ["urlToGraphNode", "http://bebo.com/Profile.jsp?MemberId=12345", "sgn://bebo.com/?pk=12345"],
  ["urlFromGraphNode", "sgn://bebo.com/?pk=12345", "rss", "http://bebo.com/api/BlogRss.jsp?MemberId=12345"],
  ["urlToGraphNode", "http://bebo.com/api/BlogRss.jsp?MemberId=12345", "sgn://bebo.com/?pk=12345"],
  ["urlToGraphNode", "http://reddit.com/user/jsmarr", "sgn://reddit.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://reddit.com/user/jsmarr/submitted.rss", "sgn://reddit.com/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://reddit.com/?ident=jsmarr", "profile", "http://reddit.com/user/jsmarr"],
  ["urlToGraphNode", "http://reddit.com/user/jsmarr", "sgn://reddit.com/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://reddit.com/?ident=jsmarr", "rss", "http://reddit.com/user/jsmarr/submitted.rss"],
  ["urlToGraphNode", "http://reddit.com/user/jsmarr/submitted.rss", "sgn://reddit.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://www.ilike.com/user/jsmarr", "sgn://ilike.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://ilike.com/user/jsmarr/songs_ilike.rss", "sgn://ilike.com/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://ilike.com/?ident=jsmarr", "profile", "http://www.ilike.com/user/jsmarr"],
  ["urlToGraphNode", "http://www.ilike.com/user/jsmarr", "sgn://ilike.com/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://ilike.com/?ident=jsmarr", "rss", "http://www.ilike.com/user/jsmarr/songs_ilike.rss"],
  ["urlToGraphNode", "http://www.ilike.com/user/jsmarr/songs_ilike.rss", "sgn://ilike.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://bradfitz.multiply.com/", "sgn://multiply.com/?ident=bradfitz"],
  ["urlFromGraphNode", "sgn://multiply.com/?ident=bradfitz", "profile", "http://bradfitz.multiply.com/"],
  ["urlToGraphNode", "http://bradfitz.multiply.com/", "sgn://multiply.com/?ident=bradfitz"],
  ["urlFromGraphNode", "sgn://multiply.com/?ident=bradfitz", "rss", "http://bradfitz.multiply.com/feed.rss"],
  ["urlToGraphNode", "http://bradfitz.multiply.com/feed.rss", "sgn://multiply.com/?ident=bradfitz"],
  ["urlToGraphNode", "http://btrott.vox.com/", "sgn://vox.com/?ident=btrott"],
  ["urlToGraphNode", "http://btrott.vox.com/profile/foaf.rdf", "sgn://vox.com/?ident=btrott"],
  ["urlToGraphNode", "http://btrott.vox.com/profile/", "sgn://vox.com/?ident=btrott"],
  ["urlToGraphNode", "http://btrott.vox.com/library/audio/6a00b8ea0714f01bc000e398d429800003.html", "sgn://vox.com/?ident=btrott"],
  ["urlFromGraphNode", "sgn://vox.com/?ident=btrott", "profile", "http://btrott.vox.com/profile/"],
  ["urlToGraphNode", "http://btrott.vox.com/profile/", "sgn://vox.com/?ident=btrott"],
  ["urlFromGraphNode", "sgn://vox.com/?ident=btrott", "foaf", "http://btrott.vox.com/profile/foaf.rdf"],
  ["urlToGraphNode", "http://btrott.vox.com/profile/foaf.rdf", "sgn://vox.com/?ident=btrott"],
  ["urlFromGraphNode", "sgn://vox.com/?ident=btrott", "atom", "http://btrott.vox.com/library/atom-full.xml"],
  ["urlToGraphNode", "http://btrott.vox.com/library/atom-full.xml", "sgn://vox.com/?ident=btrott"],
  ["urlFromGraphNode", "sgn://vox.com/?ident=btrott", "rss", "http://btrott.vox.com/library/rss-full.xml"],
  ["urlToGraphNode", "http://btrott.vox.com/library/rss-full.xml", "sgn://vox.com/?ident=btrott"],
  ["urlToGraphNode", "http://www.dopplr.com/traveller/bradfitz/", "sgn://dopplr.com/?ident=bradfitz"],
  ["urlToGraphNode", "http://dopplr.com/traveller/bradfitz/", "sgn://dopplr.com/?ident=bradfitz"],
  ["urlToGraphNode", "http://www.dopplr.com/traveller/bradfitz", "sgn://dopplr.com/?ident=bradfitz"],
  ["urlToGraphNode", "http://www.dopplr.com/traveller/bradfitz/something", "sgn://dopplr.com/?ident=bradfitz"],
  ["urlFromGraphNode", "sgn://dopplr.com/?ident=bradfitz", "profile", "http://www.dopplr.com/traveller/bradfitz"],
  ["urlToGraphNode", "http://www.dopplr.com/traveller/bradfitz", "sgn://dopplr.com/?ident=bradfitz"],
  ["urlToGraphNode", "http://c2.com/cgi/wiki?AdewaleOshineye", "sgn://c2.com/?ident=AdewaleOshineye"],
  ["urlFromGraphNode", "sgn://c2.com/?ident=AdewaleOshineye", "profile", "http://c2.com/cgi/wiki?AdewaleOshineye"],
  ["urlToGraphNode", "http://c2.com/cgi/wiki?AdewaleOshineye", "sgn://c2.com/?ident=AdewaleOshineye"],
  ["urlToGraphNode", "http://bookshelved.org/cgi-bin/wiki.pl?AdewaleOshineye", "sgn://bookshelved.org/?ident=AdewaleOshineye"],
  ["urlFromGraphNode", "sgn://bookshelved.org/?ident=AdewaleOshineye", "profile", "http://bookshelved.org/cgi-bin/wiki.pl?AdewaleOshineye"],
  ["urlToGraphNode", "http://bookshelved.org/cgi-bin/wiki.pl?AdewaleOshineye", "sgn://bookshelved.org/?ident=AdewaleOshineye"],
  ["urlToGraphNode", "http://xpdeveloper.net/xpdwiki/Wiki.jsp?page=AdewaleOshineye", "sgn://xpdeveloper.net/?ident=AdewaleOshineye"],
  ["urlFromGraphNode", "sgn://xpdeveloper.net/?ident=AdewaleOshineye", "profile", "http://xpdeveloper.net/xpdwiki/Wiki.jsp?page=AdewaleOshineye"],
  ["urlToGraphNode", "http://xpdeveloper.net/xpdwiki/Wiki.jsp?page=AdewaleOshineye", "sgn://xpdeveloper.net/?ident=AdewaleOshineye"],
  ["urlToGraphNode", "http://usemod.com/cgi-bin/mb.pl?SunirShah", "sgn://usemod.com/?ident=SunirShah"],
  ["urlFromGraphNode", "sgn://usemod.com/?ident=SunirShah", "profile", "http://usemod.com/cgi-bin/mb.pl?SunirShah"],
  ["urlToGraphNode", "http://usemod.com/cgi-bin/mb.pl?SunirShah", "sgn://usemod.com/?ident=SunirShah"],
  ["urlToGraphNode", "http://www.advogato.org/person/bradfitz", "sgn://advogato.org/?ident=bradfitz"],
  ["urlToGraphNode", "http://www.advogato.org/person/bradfitz/", "sgn://advogato.org/?ident=bradfitz"],
  ["urlToGraphNode", "http://www.advogato.org/person/bradfitz/foaf.rdf", "sgn://advogato.org/?ident=bradfitz"],
  ["urlToGraphNode", "http://www.advogato.org/person/bradfitz/foaf.rdf#me", "sgn://advogato.org/?ident=bradfitz"],
  ["urlFromGraphNode", "sgn://advogato.org/?ident=bradfitz", "foaf", "http://www.advogato.org/person/bradfitz/foaf.rdf"],
  ["urlToGraphNode", "http://www.advogato.org/person/bradfitz/foaf.rdf", "sgn://advogato.org/?ident=bradfitz"],
  ["urlFromGraphNode", "sgn://advogato.org/?ident=bradfitz", "profile", "http://www.advogato.org/person/bradfitz/"],
  ["urlToGraphNode", "http://www.advogato.org/person/bradfitz/", "sgn://advogato.org/?ident=bradfitz"],
  ["urlToGraphNode", "http://bob.weeloop.com", "sgn://weeloop.com/?ident=bob"],
  ["urlToGraphNode", "http://bob.weeloop.com/profile", "sgn://weeloop.com/?ident=bob"],
  ["urlToGraphNode", "http://bob.weeloop.com/api/post?mimeType=application/rss+xml", "sgn://weeloop.com/?ident=bob"],
  ["urlToGraphNode", "http://bob.weeloop.com/api/post?mimeType=application/atom+xml", "sgn://weeloop.com/?ident=bob"],
  ["urlToGraphNode", "http://bob.weeloop.com/foaf.rdf", "sgn://weeloop.com/?ident=bob"],
  ["urlFromGraphNode", "sgn://weeloop.com/?ident=bob", "foaf", "http://bob.weeloop.com/foaf.rdf"],
  ["urlToGraphNode", "http://bob.weeloop.com/foaf.rdf", "sgn://weeloop.com/?ident=bob"],
  ["urlFromGraphNode", "sgn://weeloop.com/?ident=bob", "profile", "http://bob.weeloop.com/profile"],
  ["urlToGraphNode", "http://bob.weeloop.com/profile", "sgn://weeloop.com/?ident=bob"],
  ["urlFromGraphNode", "sgn://weeloop.com/?ident=bob", "atom", "http://bob.weeloop.com/api/post?mimeType=application/atom+xml"],
  ["urlToGraphNode", "http://bob.weeloop.com/api/post?mimeType=application/atom+xml", "sgn://weeloop.com/?ident=bob"],
  ["urlToGraphNode", "http://www.furl.net/members/jsmarr", "sgn://furl.net/?ident=jsmarr"],
  ["urlToGraphNode", "http://furl.net/members/jsmarr/rss.xml", "sgn://furl.net/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://furl.net/?ident=jsmarr", "profile", "http://www.furl.net/members/jsmarr"],
  ["urlToGraphNode", "http://www.furl.net/members/jsmarr", "sgn://furl.net/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://furl.net/?ident=jsmarr", "rss", "http://www.furl.net/members/jsmarr/rss.xml"],
  ["urlToGraphNode", "http://www.furl.net/members/jsmarr/rss.xml", "sgn://furl.net/?ident=jsmarr"],
  ["urlToGraphNode", "http://www.dailymotion.com/jsmarr", "sgn://dailymotion.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://dailymotion.com/jsmarr", "sgn://dailymotion.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://beta.dailymotion.com/JSMarr?from=rss", "sgn://dailymotion.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://www.dailymotion.com/rss/jsmarr/1", "sgn://dailymotion.com/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://dailymotion.com/?ident=jsmarr", "profile", "http://www.dailymotion.com/jsmarr"],
  ["urlToGraphNode", "http://www.dailymotion.com/jsmarr", "sgn://dailymotion.com/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://dailymotion.com/?ident=jsmarr", "rss", "http://www.dailymotion.com/rss/jsmarr/1"],
  ["urlToGraphNode", "http://www.dailymotion.com/rss/jsmarr/1", "sgn://dailymotion.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://www.vimeo.com/jsmarr", "sgn://vimeo.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://vimeo.com/jsmarr", "sgn://vimeo.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://www.vimeo.com/jsmarr/videos/rss", "sgn://vimeo.com/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://vimeo.com/?ident=jsmarr", "profile", "http://www.vimeo.com/jsmarr"],
  ["urlToGraphNode", "http://www.vimeo.com/jsmarr", "sgn://vimeo.com/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://vimeo.com/?ident=jsmarr", "rss", "http://www.vimeo.com/jsmarr/videos/rss"],
  ["urlToGraphNode", "http://www.vimeo.com/jsmarr/videos/rss", "sgn://vimeo.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://www.disqus.com/people/jsmarr", "sgn://disqus.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://disqus.com/people/jsmarr/comments.rss", "sgn://disqus.com/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://disqus.com/?ident=jsmarr", "profile", "http://www.disqus.com/people/jsmarr"],
  ["urlToGraphNode", "http://www.disqus.com/people/jsmarr", "sgn://disqus.com/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://disqus.com/?ident=jsmarr", "rss", "http://www.disqus.com/people/jsmarr/comments.rss"],
  ["urlToGraphNode", "http://www.disqus.com/people/jsmarr/comments.rss", "sgn://disqus.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://www.rateitall.com/jsmarr", "sgn://rateitall.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://www.rateitall.com/Profile.aspx?userID=12345", "sgn://rateitall.com/?pk=12345"],
  ["urlToGraphNode", "http://www.rateitall.com/rss-u-jsmarr.aspx", "sgn://rateitall.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://www.rateitall.com/rss-u-12345.aspx", "sgn://rateitall.com/?pk=12345"],
  ["urlFromGraphNode", "sgn://rateitall.com/?ident=jsmarr", "profile", "http://www.rateitall.com/jsmarr"],
  ["urlToGraphNode", "http://www.rateitall.com/jsmarr", "sgn://rateitall.com/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://rateitall.com/?pk=12345", "profile", "http://www.rateitall.com/Profile.aspx?userID=12345"],
  ["urlToGraphNode", "http://www.rateitall.com/Profile.aspx?userID=12345", "sgn://rateitall.com/?pk=12345"],
  ["urlFromGraphNode", "sgn://rateitall.com/?ident=jsmarr", "rss", "http://www.rateitall.com/rss-u-jsmarr.aspx"],
  ["urlToGraphNode", "http://www.rateitall.com/rss-u-jsmarr.aspx", "sgn://rateitall.com/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://rateitall.com/?pk=12345", "rss", "http://www.rateitall.com/rss-u-12345.aspx"],
  ["urlToGraphNode", "http://www.rateitall.com/rss-u-12345.aspx", "sgn://rateitall.com/?pk=12345"],
  ["urlToGraphNode", "http://www.rateitall.com/usercommentsrss.aspx?RI=jsmarr", "sgn://rateitall.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://www.rateitall.com/usercommentsrss.aspx?RI=12345", "sgn://rateitall.com/?pk=12345"],
  ["urlToGraphNode", "http://www.slideshare.net/jsmarr", "sgn://slideshare.net/?ident=jsmarr"],
  ["urlToGraphNode", "http://slideshare.net/rss/user/jsmarr", "sgn://slideshare.net/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://slideshare.net/?ident=jsmarr", "profile", "http://www.slideshare.net/jsmarr"],
  ["urlToGraphNode", "http://www.slideshare.net/jsmarr", "sgn://slideshare.net/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://slideshare.net/?ident=jsmarr", "rss", "http://www.slideshare.net/rss/user/jsmarr"],
  ["urlToGraphNode", "http://www.slideshare.net/rss/user/jsmarr", "sgn://slideshare.net/?ident=jsmarr"],
  ["urlToGraphNode", "http://blog.sina.com.cn/jsmarr", "sgn://blog.sina.com.cn/?ident=jsmarr"],
  ["urlToGraphNode", "http://blog.sina.com.cn/rss/jsmarr.xml", "sgn://blog.sina.com.cn/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://blog.sina.com.cn/?ident=jsmarr", "profile", "http://blog.sina.com.cn/jsmarr"],
  ["urlToGraphNode", "http://blog.sina.com.cn/jsmarr", "sgn://blog.sina.com.cn/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://blog.sina.com.cn/?ident=jsmarr", "rss", "http://blog.sina.com.cn/rss/jsmarr.xml"],
  ["urlToGraphNode", "http://blog.sina.com.cn/rss/jsmarr.xml", "sgn://blog.sina.com.cn/?ident=jsmarr"],
  ["urlToGraphNode", "http://hi.baidu.com/jsmarr", "sgn://hi.baidu.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://hi.baidu.com/jsmarr/rss", "sgn://hi.baidu.com/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://hi.baidu.com/?ident=jsmarr", "profile", "http://hi.baidu.com/jsmarr"],
  ["urlToGraphNode", "http://hi.baidu.com/jsmarr", "sgn://hi.baidu.com/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://hi.baidu.com/?ident=jsmarr", "rss", "http://hi.baidu.com/jsmarr/rss"],
  ["urlToGraphNode", "http://hi.baidu.com/jsmarr/rss", "sgn://hi.baidu.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://jsmarr.blogbus.com/", "sgn://blogbus.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://jsmarr.blogbus.com/index.rdf", "sgn://blogbus.com/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://blogbus.com/?ident=jsmarr", "profile", "http://jsmarr.blogbus.com/"],
  ["urlToGraphNode", "http://jsmarr.blogbus.com/", "sgn://blogbus.com/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://blogbus.com/?ident=jsmarr", "rss", "http://jsmarr.blogbus.com/index.rdf"],
  ["urlToGraphNode", "http://jsmarr.blogbus.com/index.rdf", "sgn://blogbus.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://planeta.rambler.ru/users/alex.nec.ru/", "sgn://planeta.rambler.ru/?ident=alex.nec.ru"],
  ["urlToGraphNode", "http://planeta.rambler.ru/users/alex.nec.RU", "sgn://planeta.rambler.ru/?ident=alex.nec.ru"],
  ["urlFromGraphNode", "sgn://planeta.rambler.ru/?ident=alex.nec.ru", "foaf", "http://planeta.rambler.ru/users/alex.nec.ru/friends/foaf/"],
  ["urlToGraphNode", "http://planeta.rambler.ru/users/alex.nec.ru/friends/foaf/", "sgn://planeta.rambler.ru/?ident=alex.nec.ru"],
  ["urlFromGraphNode", "sgn://planeta.rambler.ru/?ident=alex.nec.ru", "rss", "http://planeta.rambler.ru/users/alex.nec.ru/rss/"],
  ["urlToGraphNode", "http://planeta.rambler.ru/users/alex.nec.ru/rss/", "sgn://planeta.rambler.ru/?ident=alex.nec.ru"],
  ["urlToGraphNode", "http://d.hatena.ne.jp/akatori777", "sgn://d.hatena.ne.jp/?ident=akatori777"],
  ["urlToGraphNode", "http://d.hatena.ne.jp/akatori777/", "sgn://d.hatena.ne.jp/?ident=akatori777"],
  ["urlToGraphNode", "http://d.hatena.ne.jp/AKatori777/", "sgn://d.hatena.ne.jp/?ident=AKatori777"],
  ["urlToGraphNode", "http://d.hatena.ne.jp/A-Sky/", "sgn://d.hatena.ne.jp/?ident=A-Sky"],
  ["urlToGraphNode", "http://d.hatena.ne.jp/akatori777/foaf", "sgn://d.hatena.ne.jp/?ident=akatori777"],
  ["urlToGraphNode", "http://d.hatena.ne.jp/akatori777/20090101/11920734", "sgn://d.hatena.ne.jp/?ident=akatori777"],
  ["urlFromGraphNode", "sgn://d.hatena.ne.jp/?ident=akatori777", "profile", "http://d.hatena.ne.jp/akatori777/"],
  ["urlToGraphNode", "http://d.hatena.ne.jp/akatori777/", "sgn://d.hatena.ne.jp/?ident=akatori777"],
  ["urlFromGraphNode", "sgn://d.hatena.ne.jp/?ident=akatori777", "foaf", "http://d.hatena.ne.jp/akatori777/foaf"],
  ["urlToGraphNode", "http://d.hatena.ne.jp/akatori777/foaf", "sgn://d.hatena.ne.jp/?ident=akatori777"],
  ["urlFromGraphNode", "sgn://d.hatena.ne.jp/?ident=akatori777", "rss", "http://d.hatena.ne.jp/akatori777/rss"],
  ["urlToGraphNode", "http://d.hatena.ne.jp/akatori777/rss", "sgn://d.hatena.ne.jp/?ident=akatori777"],
  ["urlToGraphNode", "http://www.mojageneracja.pl/13192415/", "sgn://mojageneracja.pl/?pk=13192415"],
  ["urlToGraphNode", "http://www.mojageneracja.pl/13192415/something", "sgn://mojageneracja.pl/?pk=13192415"],
  ["urlFromGraphNode", "sgn://mojageneracja.pl/?pk=13192415", "profile", "http://www.mojageneracja.pl/13192415/"],
  ["urlToGraphNode", "http://www.mojageneracja.pl/13192415/", "sgn://mojageneracja.pl/?pk=13192415"],
  ["urlFromGraphNode", "sgn://mojageneracja.pl/?pk=13192415", "rss", "http://www.mojageneracja.pl/13192415/rss"],
  ["urlToGraphNode", "http://www.mojageneracja.pl/13192415/rss", "sgn://mojageneracja.pl/?pk=13192415"],
  ["urlToGraphNode", "http://www.goodreads.com/user/show/1150869", "sgn://goodreads.com/?pk=1150869"],
  ["urlToGraphNode", "http://goodreads.com/user/show/1150869", "sgn://goodreads.com/?pk=1150869"],
  ["urlToGraphNode", "http://www.goodreads.com/review/list_rss/1150869", "sgn://goodreads.com/?pk=1150869"],
  ["urlFromGraphNode", "sgn://goodreads.com/?pk=1150869", "profile", "http://www.goodreads.com/user/show/1150869"],
  ["urlToGraphNode", "http://www.goodreads.com/user/show/1150869", "sgn://goodreads.com/?pk=1150869"],
  ["urlFromGraphNode", "sgn://goodreads.com/?pk=1150869", "rss", "http://www.goodreads.com/review/list_rss/1150869"],
  ["urlToGraphNode", "http://www.goodreads.com/review/list_rss/1150869", "sgn://goodreads.com/?pk=1150869"],
  ["urlToGraphNode", "http://tungle.me/jsmarr", "sgn://tungle.me/?ident=jsmarr"],
  ["urlToGraphNode", "http://tgl.me/jsmarr", "sgn://tungle.me/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://tungle.me/?ident=jsmarr", "profile", "http://tungle.me/jsmarr"],
  ["urlToGraphNode", "http://tungle.me/jsmarr", "sgn://tungle.me/?ident=jsmarr"],
  ["urlToGraphNode", "http://tripit.com/people/Adam+Smith", "sgn://tripit.com/?ident=adam+smith"],
  ["urlToGraphNode", "http://tripit.com/people/aNOTher-person/", "sgn://tripit.com/?ident=another-person"],
  ["urlToGraphNode", "http://tripit.com/people/some.1", "sgn://tripit.com/?ident=some.1"],
  ["urlToGraphNode", "http://www.tripit.com/people/just_me/nothing", "sgn://tripit.com/?ident=just_me"],
  ["urlToGraphNode", "http://www.tripit.com/people/meEE.123", "sgn://tripit.com/?ident=meee.123"],
  ["urlToGraphNode", "http://www.tripit.com/people/trying?what", "sgn://tripit.com/?ident=trying"],
  ["urlFromGraphNode", "sgn://tripit.com/?ident=foobar", "profile", "http://tripit.com/people/foobar"],
  ["urlToGraphNode", "http://tripit.com/people/foobar", "sgn://tripit.com/?ident=foobar"],
  ["pairToGraphNode", "spin.de", "Warp", "sgn://spin.de/?ident=warp"],
  ["urlToGraphNode", "http://www.spin.de/hp/Warp", "sgn://spin.de/?ident=warp"],
  ["urlToGraphNode", "http://www.spin.de/hp/warp", "sgn://spin.de/?ident=warp"],
  ["urlToGraphNode", "http://www.spin.de/hp/Warp/", "sgn://spin.de/?ident=warp"],
  ["urlToGraphNode", "http://www.spin.de/hp/Warp/blog", "sgn://spin.de/?ident=warp"],
  ["urlToGraphNode", "http://www.spin.de/foaf/Warp", "sgn://spin.de/?ident=warp"],
  ["urlToGraphNode", "http://www.spin.de/hp/xITO!!!/", "sgn://spin.de/?ident=xito!!!"],
  ["urlToGraphNode", "http://www.spin.de/hp/*xordon*/", "sgn://spin.de/?ident=*xordon*"],
  ["urlToGraphNode", "http://www.spin.de/hp/,62b", "sgn://spin.de/?pk=62b"],
  ["urlToGraphNode", "http://www.spin.de/hp/,62b/blog", "sgn://spin.de/?pk=62b"],
  ["urlFromGraphNode", "sgn://spin.de/?ident=warp", "foaf", "http://www.spin.de/foaf/warp"],
  ["urlToGraphNode", "http://www.spin.de/foaf/warp", "sgn://spin.de/?ident=warp"],
  ["urlFromGraphNode", "sgn://spin.de/?pk=62b", "foaf", "http://www.spin.de/foaf/,62b"],
  ["urlToGraphNode", "http://www.spin.de/foaf/,62b", "sgn://spin.de/?pk=62b"],
  ["urlFromGraphNode", "sgn://spin.de/?ident=warp", "profile", "http://www.spin.de/hp/warp/"],
  ["urlToGraphNode", "http://www.spin.de/hp/warp/", "sgn://spin.de/?ident=warp"],
  ["urlFromGraphNode", "sgn://spin.de/?ident=warp", "blog", "http://www.spin.de/hp/warp/blog"],
  ["urlToGraphNode", "http://www.spin.de/hp/warp/blog", "sgn://spin.de/?ident=warp"],
  ["urlToGraphNode", "http://bradfitz.stumbleupon.com/", "sgn://stumbleupon.com/?ident=bradfitz"],
  ["urlToGraphNode", "http://bradfitz.stumbleupon.com/blog/", "sgn://stumbleupon.com/?ident=bradfitz"],
  ["urlToGraphNode", "http://www.stumbleupon.com/stumbler/bradfitz/", "sgn://stumbleupon.com/?ident=bradfitz"],
  ["urlToGraphNode", "http://www.stumbleupon.com/stumbler/bradfitz/blog/", "sgn://stumbleupon.com/?ident=bradfitz"],
  ["urlToGraphNode", "http://rss.stumbleupon.com/user/bradfitz/favorites", "sgn://stumbleupon.com/?ident=bradfitz"],
  ["urlFromGraphNode", "sgn://stumbleupon.com/?ident=bradfitz", "profile", "http://bradfitz.stumbleupon.com"],
  ["urlToGraphNode", "http://bradfitz.stumbleupon.com", "sgn://stumbleupon.com/?ident=bradfitz"],
  ["urlFromGraphNode", "sgn://stumbleupon.com/?ident=bradfitz", "rss", "http://rss.stumbleupon.com/user/bradfitz/favorites"],
  ["urlToGraphNode", "http://rss.stumbleupon.com/user/bradfitz/favorites", "sgn://stumbleupon.com/?ident=bradfitz"],
  ["urlToGraphNode", "http://www.stumbleupon.com/syndicate.php?stumbler=bradfitz", "sgn://stumbleupon.com/?ident=bradfitz"],
  ["urlToGraphNode", "http://www.threadless.com/profile/149253/Aunalis", "sgn://threadless.com/?ident=149253/aunalis"],
  ["urlToGraphNode", "http://www.threadless.com/profile/149253", "sgn://threadless.com/?pk=149253"],
  ["urlFromGraphNode", "sgn://threadless.com/?pk=149253", "profile", "http://www.threadless.com/profile/149253"],
  ["urlToGraphNode", "http://www.threadless.com/profile/149253", "sgn://threadless.com/?pk=149253"],
  ["urlFromGraphNode", "sgn://threadless.com/?ident=149253/aunalis", "profile", "http://www.threadless.com/profile/149253/aunalis"],
  ["urlToGraphNode", "http://www.threadless.com/profile/149253/aunalis", "sgn://threadless.com/?ident=149253/aunalis"],
  ["urlToGraphNode", "http://www.threadless.com/rss/blog/149253/Aunalis", "sgn://threadless.com/?ident=149253/aunalis"],
  ["urlToGraphNode", "http://www.threadless.com/rss/blog/149253", "sgn://threadless.com/?pk=149253"],
  ["urlFromGraphNode", "sgn://threadless.com/?ident=149253/aunalis", "rss", "http://www.threadless.com/rss/blog/149253/aunalis"],
  ["urlToGraphNode", "http://www.threadless.com/rss/blog/149253/aunalis", "sgn://threadless.com/?ident=149253/aunalis"],
  ["urlFromGraphNode", "sgn://threadless.com/?pk=149253", "rss", "http://www.threadless.com/rss/blog/149253"],
  ["urlToGraphNode", "http://www.threadless.com/rss/blog/149253", "sgn://threadless.com/?pk=149253"],
  ["urlToGraphNode", "http://www.threadless.com/profile/149253/Aunalis/archive", "sgn://threadless.com/?ident=149253/aunalis"],
  ["urlToGraphNode", "http://www.threadless.com/profile/149253/Aunalis/blogs", "sgn://threadless.com/?ident=149253/aunalis"],
  ["urlToGraphNode", "http://www.threadless.com/profile/149253/Aunalis/blog/", "sgn://threadless.com/?ident=149253/aunalis"],
  ["urlToGraphNode", "http://threadless.com/profile/226507/Legoman", "sgn://threadless.com/?ident=226507/legoman"],
  ["urlToGraphNode", "http://media.threadless.com/profile/284208/Neiko", "sgn://threadless.com/?ident=284208/neiko"],
  ["urlFromGraphNode", "sgn://threadless.com/?ident=149253/aunalis", "blog", "http://www.threadless.com/profile/149253/aunalis/blogs"],
  ["urlToGraphNode", "http://www.threadless.com/profile/149253/aunalis/blogs", "sgn://threadless.com/?ident=149253/aunalis"],
  ["urlToGraphNode", "http://people.tribe.net/bayareadj/foaf", "sgn://tribe.net/?ident=bayareadj"],
  ["urlToGraphNode", "http://people.tribe.net/bayareadj/", "sgn://tribe.net/?ident=bayareadj"],
  ["urlToGraphNode", "http://people.tribe.net/bayareadj", "sgn://tribe.net/?ident=bayareadj"],
  ["urlToGraphNode", "http://people.tribe.net/079d0f9a-ed4b-4d2d-8290-a65a3df32342", "sgn://tribe.net/?pk=079d0f9a-ed4b-4d2d-8290-a65a3df32342"],
  ["urlToGraphNode", "http://people.tribe.net/079d0f9a-ed4b-4d2d-8290-a65a3df32342/foaf", "sgn://tribe.net/?pk=079d0f9a-ed4b-4d2d-8290-a65a3df32342"],
  ["urlToGraphNode", "http://people.tribe.net/079d0f9a-ed4b-4d2d-8290-a65a3df32342/blog", "sgn://tribe.net/?pk=079d0f9a-ed4b-4d2d-8290-a65a3df32342"],
  ["urlToGraphNode", "http://www.people.tribe.net/c72b358e-1f53-407e-aa98-5b18c70072e1/blog", "sgn://tribe.net/?pk=c72b358e-1f53-407e-aa98-5b18c70072e1"],
  ["urlFromGraphNode", "sgn://tribe.net/?ident=bayareadj", "foaf", "http://people.tribe.net/bayareadj/foaf"],
  ["urlToGraphNode", "http://people.tribe.net/bayareadj/foaf", "sgn://tribe.net/?ident=bayareadj"],
  ["urlFromGraphNode", "sgn://tribe.net/?pk=079d0f9a-ed4b-4d2d-8290-a65a3df32342", "foaf", "http://people.tribe.net/079d0f9a-ed4b-4d2d-8290-a65a3df32342/foaf"],
  ["urlToGraphNode", "http://people.tribe.net/079d0f9a-ed4b-4d2d-8290-a65a3df32342/foaf", "sgn://tribe.net/?pk=079d0f9a-ed4b-4d2d-8290-a65a3df32342"],
  ["urlFromGraphNode", "sgn://tribe.net/?ident=bayareadj", "profile", "http://people.tribe.net/bayareadj"],
  ["urlToGraphNode", "http://people.tribe.net/bayareadj", "sgn://tribe.net/?ident=bayareadj"],
  ["urlFromGraphNode", "sgn://tribe.net/?pk=079d0f9a-ed4b-4d2d-8290-a65a3df32342", "profile", "http://people.tribe.net/079d0f9a-ed4b-4d2d-8290-a65a3df32342"],
  ["urlToGraphNode", "http://people.tribe.net/079d0f9a-ed4b-4d2d-8290-a65a3df32342", "sgn://tribe.net/?pk=079d0f9a-ed4b-4d2d-8290-a65a3df32342"],
  ["urlToGraphNode", "http://twitter.com/bob", "sgn://twitter.com/?ident=bob"],
  ["urlToGraphNode", "http://twitter.com/Bob", "sgn://twitter.com/?ident=bob"],
  ["urlToGraphNode", "http://twitter.com/Bob/", "sgn://twitter.com/?ident=bob"],
  ["urlToGraphNode", "http://twitter.com/#!/Bob/", "sgn://twitter.com/?ident=bob"],
  ["urlToGraphNode", "https://twitter.com/bob", "sgn://twitter.com/?ident=bob"],
  ["urlToGraphNode", "https://twitter.com/BOB/", "sgn://twitter.com/?ident=bob"],
  ["urlToGraphNode", "https://twitter.com/#!/Bob/", "sgn://twitter.com/?ident=bob"],
  ["urlToGraphNode", "http://explore.twitter.com/bob/with_friends", "sgn://twitter.com/?ident=bob"],
  ["urlToGraphNode", "http://greekshow.twitter.com/bob/with_friends", "sgn://twitter.com/?ident=bob"],
  ["urlFromGraphNode", "sgn://twitter.com/?ident=brad", "profile", "http://twitter.com/brad"],
  ["urlToGraphNode", "http://twitter.com/brad", "sgn://twitter.com/?ident=brad"],
  ["urlFromGraphNode", "sgn://twitter.com/?ident=brad", "rss", "http://twitter.com/statuses/user_timeline/brad.rss"],
  ["urlToGraphNode", "http://twitter.com/statuses/user_timeline/brad.rss", "sgn://twitter.com/?ident=brad"],
  ["urlFromGraphNode", "sgn://twitter.com/?ident=brad", "atom", "http://twitter.com/statuses/user_timeline/brad.atom"],
  ["urlToGraphNode", "http://twitter.com/statuses/user_timeline/brad.atom", "sgn://twitter.com/?ident=brad"],
  ["urlToGraphNode", "http://twitter.com/friends/foo", "http://twitter.com/friends/foo"],
  ["urlToGraphNode", "http://twitter.com/friends", "http://twitter.com/friends"],
  ["urlToGraphNode", "http://twitter.com/statuses/user_timeline/BRAD.rss", "sgn://twitter.com/?ident=brad"],
  ["urlToGraphNode", "http://twitter.com/statuses/user_timeline/1234.rss", "sgn://twitter.com/?pk=1234"],
  ["urlToGraphNode", "http://twitter.com/friends/ids/bradfitz.xml", "sgn://twitter.com/?ident=bradfitz"],
  ["urlToGraphNode", "http://twitter.com/friends/ids/BRADFITZ.json", "sgn://twitter.com/?ident=bradfitz"],
  ["urlToGraphNode", "http://twitter.com/friends/ids.xml?screen_name=lisaphillips", "sgn://twitter.com/?ident=lisaphillips"],
  ["urlToGraphNode", "http://twitter.com/friends/ids.json?screen_name=lisaphillips", "sgn://twitter.com/?ident=lisaphillips"],
  ["urlToGraphNode", "http://wakoopa.com/crabbydata", "sgn://wakoopa.com/?ident=crabbydata"],
  ["urlToGraphNode", "http://wakoopa.com/CrabbyDATA/feed/foo", "sgn://wakoopa.com/?ident=crabbydata"],
  ["urlFromGraphNode", "sgn://wakoopa.com/?ident=crabbydata", "profile", "http://wakoopa.com/crabbydata"],
  ["urlToGraphNode", "http://wakoopa.com/crabbydata", "sgn://wakoopa.com/?ident=crabbydata"],
  ["urlToGraphNode", "http://wakoopa.com/software/quartz-wm", "sgn://software.wakoopa.com/?ident=quartz-wm"],
  ["urlToGraphNode", "http://wakoopa.com/software/LAUNCHER?guid=2008-05-28%2001%3A05%3A06", "sgn://software.wakoopa.com/?ident=launcher"],
  ["urlFromGraphNode", "sgn://software.wakoopa.com/?ident=quartz-wm", "profile", "http://wakoopa.com/software/quartz-wm"],
  ["urlToGraphNode", "http://wakoopa.com/software/quartz-wm", "sgn://software.wakoopa.com/?ident=quartz-wm"],
  ["urlToGraphNode", "http://foo.wordpress.com/", "sgn://wordpress.com/?ident=foo"],
  ["urlToGraphNode", "http://www.foo.wordpress.com/", "sgn://wordpress.com/?ident=foo"],
  ["urlToGraphNode", "http://pt-br.wordpress.com/", "http://pt-br.wordpress.com/"],
  ["urlToGraphNode", "http://de.wordpress.com/", "http://de.wordpress.com/"],
  ["urlFromGraphNode", "sgn://wordpress.com/?ident=foo", "blog", "http://foo.wordpress.com/"],
  ["urlToGraphNode", "http://foo.wordpress.com/", "sgn://wordpress.com/?ident=foo"],
  ["urlToGraphNode", "http://jsmarr.yelp.com", "sgn://yelp.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://www.yelp.com/user_details?userid=Dk2IkchUjADbrC05sdsAVQ", "sgn://yelp.com/?pk=Dk2IkchUjADbrC05sdsAVQ"],
  ["urlToGraphNode", "http://yelp.com/user_details?userid=Dk2IkchUjADbrC05sdsAVQ", "sgn://yelp.com/?pk=Dk2IkchUjADbrC05sdsAVQ"],
  ["urlToGraphNode", "http://www.yelp.com/syndicate/user/Dk2IkchUjADbrC05sdsAVQ/rss.xml", "sgn://yelp.com/?pk=Dk2IkchUjADbrC05sdsAVQ"],
  ["urlToGraphNode", "http://yelp.com/syndicate/user/Dk2IkchUjADbrC05sdsAVQ/rss.xml", "sgn://yelp.com/?pk=Dk2IkchUjADbrC05sdsAVQ"],
  ["urlFromGraphNode", "sgn://yelp.com/?pk=Dk2IkchUjADbrC05sdsAVQ", "rss", "http://www.yelp.com/syndicate/user/Dk2IkchUjADbrC05sdsAVQ/rss.xml"],
  ["urlToGraphNode", "http://www.yelp.com/syndicate/user/Dk2IkchUjADbrC05sdsAVQ/rss.xml", "sgn://yelp.com/?pk=Dk2IkchUjADbrC05sdsAVQ"],
  ["urlFromGraphNode", "sgn://yelp.com/?pk=Dk2IkchUjADbrC05sdsAVQ", "profile", "http://www.yelp.com/user_details?userid=Dk2IkchUjADbrC05sdsAVQ"],
  ["urlToGraphNode", "http://www.yelp.com/user_details?userid=Dk2IkchUjADbrC05sdsAVQ", "sgn://yelp.com/?pk=Dk2IkchUjADbrC05sdsAVQ"],
  ["urlFromGraphNode", "sgn://yelp.com/?ident=jsmarr", "profile", "http://jsmarr.yelp.com"],
  ["urlToGraphNode", "http://jsmarr.yelp.com", "sgn://yelp.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://jsmarr-hyphen.yelp.com", "sgn://yelp.com/?ident=jsmarr-hyphen"],
  ["urlToGraphNode", "http://www.yelp.com/user_details?userid=nkN_do3fJ9xekchVa-v68A", "sgn://yelp.com/?pk=nkN_do3fJ9xekchVa-v68A"],
  ["urlToGraphNode", "http://www.zooomr.com/photos", "http://www.zooomr.com/photos"],
  ["urlToGraphNode", "http://www.zooomr.com/people/", "http://www.zooomr.com/people/"],
  ["urlToGraphNode", "http://www.zooomr.com/photos/jsmarr", "sgn://zooomr.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://www.zooomr.com/people/jsmarr", "sgn://zooomr.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://www.zooomr.com/people/jsmarr/fans", "sgn://zooomr.com/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://zooomr.com/?ident=jsmarr", "profile", "http://www.zooomr.com/people/jsmarr/"],
  ["urlToGraphNode", "http://www.zooomr.com/people/jsmarr/", "sgn://zooomr.com/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://zooomr.com/?ident=jsmarr", "rss", "http://www.zooomr.com/services/feeds/public_photos/?id=jsmarr&format=rss_200"],
  ["urlToGraphNode", "http://www.zooomr.com/services/feeds/public_photos/?id=jsmarr&format=rss_200", "sgn://zooomr.com/?ident=jsmarr"],
  ["urlFromGraphNode", "sgn://zooomr.com/?ident=jsmarr", "content", "http://www.zooomr.com/photos/jsmarr/"],
  ["urlToGraphNode", "http://www.zooomr.com/photos/jsmarr/", "sgn://zooomr.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://cn.zooomr.com/453@Z01/", "sgn://zooomr.com/?pk=453@Z01"],
  ["urlFromGraphNode", "sgn://zooomr.com/?pk=453@Z01", "rss", "http://www.zooomr.com/services/feeds/public_photos/?id=453@Z01&format=rss_200"],
  ["urlToGraphNode", "http://www.zooomr.com/services/feeds/public_photos/?id=453@Z01&format=rss_200", "sgn://zooomr.com/?pk=453@Z01"],
  ["urlFromGraphNode", "sgn://zooomr.com/?pk=453@Z01", "profile", "http://www.zooomr.com/people/453@Z01/"],
  ["urlToGraphNode", "http://www.zooomr.com/people/453@Z01/", "sgn://zooomr.com/?pk=453@Z01"],
  ["urlToGraphNode", "http://cn.zooomr.com/photos/jsmarr", "sgn://zooomr.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://de.zooomr.com/photos/jsmarr", "sgn://zooomr.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://es.zooomr.com/photos/jsmarr", "sgn://zooomr.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://it.zooomr.com/photos/jsmarr", "sgn://zooomr.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://jp.zooomr.com/photos/jsmarr", "sgn://zooomr.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://pt-br.zooomr.com/photos/jsmarr", "sgn://zooomr.com/?ident=jsmarr"],
  ["urlToGraphNode", "http://cn.zooomr.com/anniebluesky", "sgn://zooomr.com/?ident=anniebluesky"],
  ["urlToGraphNode", "http://de.zooomr.com/5uspect", "sgn://zooomr.com/?ident=5uspect"],
  ["urlToGraphNode", "http://de.zooomr.com/bear11", "sgn://zooomr.com/?ident=bear11"],
  ["urlToGraphNode", "http://cn.zooomr.com/abc/fans/", "sgn://zooomr.com/?ident=abc"],
  ["urlToGraphNode", "http://pt.zooomr.com/abc/statuses/3d64a48d61/foo-bar", "sgn://zooomr.com/?ident=abc"],
  ["urlToGraphNode", "http://cn.zooomr.com/abc/xxxx/", "http://cn.zooomr.com/abc/xxxx/"],
  ["urlToGraphNode", "http://it.zooomr.com/ontheroad/statuses/f5638736d6/", "sgn://zooomr.com/?ident=ontheroad"],
  ["urlToGraphNode", "http://www.zooomr.com/zipline/abc/statuses/2d516020e2/some-message/", "sgn://zooomr.com/?ident=abc"],
  ["urlToGraphNode", "http://de.zooomr.com/kristopher/page2/?acat=1", "sgn://zooomr.com/?ident=kristopher"]
];
