# Auto-generated test data from sites/*.js test sections at bottom.
var nodemapper_tests = [
  "to_sgn", "http://www.amazon.com/gp/pdp/profile/A2Q1GI13N0TVRC", "sgn://amazon.com/?pk=A2Q1GI13N0TVRC",
  "to_sgn", "http://amazon.com/gp/pdp/profile/A2Q1GI13N0TVRC", "sgn://amazon.com/?pk=A2Q1GI13N0TVRC",
  "to_sgn", "http://www.amazon.co.uk/gp/pdp/profile/A2Q1GI13N0TVRC", "sgn://amazon.com/?pk=A2Q1GI13N0TVRC",
  "to_sgn", "http://www.amazon.com/rss/people/A2Q1GI13N0TVRC/reviews", "sgn://amazon.com/?pk=A2Q1GI13N0TVRC",
  "from_sgn", "profile", "sgn://amazon.com/?pk=A2Q1GI13N0TVRC", "http://www.amazon.com/gp/pdp/profile/A2Q1GI13N0TVRC",
  "from_sgn", "rss", "sgn://amazon.com/?pk=A2Q1GI13N0TVRC", "http://www.amazon.com/rss/people/A2Q1GI13N0TVRC/reviews",
  "to_sgn", "aim:goim?message=Hi!+I+found+you+on+Xxxx...&screenname=Foo%20Bar", "sgn://aol.com/?ident=foobar",
  "to_sgn", "aim:GoIM?screenname=fooBar", "sgn://aol.com/?ident=foobar",
  "to_sgn", "aim:goim?Screenname=foo+Bar", "sgn://aol.com/?ident=foobar",
  "to_sgn", "aim:goim?screenname=foo%20bar", "sgn://aol.com/?ident=foobar",
  "to_sgn", "aim:fooBar", "sgn://aol.com/?ident=foobar",
  "to_sgn", "aim:foo+Bar", "sgn://aol.com/?ident=foobar",
  "to_sgn", "http://www.aimpages.com/foobar/profile.html", "sgn://aol.com/?ident=foobar",
  "to_sgn", "http://www.aimpages.com//foobar/profile.html", "sgn://aol.com/?ident=foobar",
  "to_sgn", "http://www.aimpages.com/foobar/", "sgn://aol.com/?ident=foobar",
  "to_sgn", "http://www.aimpages.com/foo+bar/", "sgn://aol.com/?ident=foobar",
  "to_sgn", "http://www.aimpages.com/foobar", "sgn://aol.com/?ident=foobar",
  "to_sgn", "http://openid.aol.com/foobar", "sgn://aol.com/?ident=foobar",
  "to_sgn", "http://openid.aol.com/foobar/", "sgn://aol.com/?ident=foobar",
  "to_sgn", "http://profiles.aim.com/foobar", "sgn://aol.com/?ident=foobar",
  "from_sgn", "openid", "sgn://aol.com/?ident=foobar", "http://openid.aol.com/foobar",
  "from_sgn", "chat", "sgn://aol.com/?ident=foobar", "aim:GoIM?screenname=foobar",
  "from_sgn", "profile", "sgn://aol.com/?ident=foobar", "http://profiles.aim.com/foobar",
  "to_sgn", "http://pictures.aol.com/galleries/josephsmarr", "sgn://pictures.aol.com/?ident=josephsmarr",
  "from_sgn", "profile", "sgn://pictures.aol.com/?ident=josephsmarr", "http://pictures.aol.com/galleries/josephsmarr",
  "from_sgn", "atom", "sgn://pictures.aol.com/?ident=josephsmarr", "http://pictures.aol.com/galleries/josephsmarr/atom.xml",
  "to_sgn", "http://www.blogger.com/profile/123", "sgn://blogger.com/?pk=123",
  "from_sgn", "profile", "sgn://blogger.com/?pk=123", "http://www.blogger.com/profile/123",
  "to_sgn", "http://foo.blogspot.com/", "sgn://blogspot.com/?ident=foo",
  "to_sgn", "http://www.foo.blogspot.com/", "sgn://blogspot.com/?ident=foo",
  "to_sgn", "http://foo.blogspot.com/path/blah", "sgn://blogspot.com/?ident=foo",
  "from_sgn", "content", "sgn://blogspot.com/?ident=foo", "http://foo.blogspot.com/",
  "from_sgn", "blog", "sgn://blogspot.com/?ident=foo", "http://foo.blogspot.com/",
  "to_sgn", "http://www.facebook.com/profile.php?id=500033387", "sgn://facebook.com/?pk=500033387",
  "to_sgn", "http://www.facebook.com/people/Brad_Fitzpatrick/500033387", "sgn://facebook.com/?ident=Brad_Fitzpatrick/500033387",
  "to_sgn", "http://www.facebook.com/p/Brad_Fitzpatrick/500033387", "sgn://facebook.com/?ident=Brad_Fitzpatrick/500033387",
  "to_sgn", "http://facebook.com/p/Brad_Fitzpatrick/500033387", "sgn://facebook.com/?ident=Brad_Fitzpatrick/500033387",
  "to_sgn", "http://washington.facebook.com/profile.php?id=123&ref=np", "sgn://facebook.com/?pk=123",
  "from_sgn", "profile", "sgn://facebook.com/?pk=500033387", "http://www.facebook.com/profile.php?id=500033387",
  "from_sgn", "profile", "sgn://facebook.com/?ident=Brad_Fitzpatrick/500033387", "http://www.facebook.com/people/Brad_Fitzpatrick/500033387",
  "to_sgn", "http://www.flickr.com/people/crucially", "sgn://flickr.com/?ident=crucially",
  "to_sgn", "http://www.flickr.com/people/crucially/", "sgn://flickr.com/?ident=crucially",
  "to_sgn", "http://www.flickr.com/photos/crucially", "sgn://flickr.com/?ident=crucially",
  "to_sgn", "http://www.flickr.com/photos/crucially/", "sgn://flickr.com/?ident=crucially",
  "to_sgn", "http://www.flickr.com/photos/15738836@N00/", "sgn://flickr.com/?pk=15738836@N00",
  "to_sgn", "http://www.flickr.com/people/15738836@N00/", "sgn://flickr.com/?pk=15738836@N00",
  "from_sgn", "profile", "sgn://flickr.com/?ident=crucially", "http://www.flickr.com/people/crucially/",
  "from_sgn", "content", "sgn://flickr.com/?ident=crucially", "http://www.flickr.com/photos/crucially/",
  "from_sgn", "addfriend", "sgn://flickr.com/?ident=crucially", "http://www.flickr.com/people/crucially/relationship/",
  "from_sgn", "rss", "sgn://flickr.com/?pk=15738836@N00", "http://api.flickr.com/services/feeds/photos_public.gne?id=15738836@N00&lang=en-us&format=rss_200",
  "from_sgn", "atom", "sgn://flickr.com/?pk=15738836@N00", "http://api.flickr.com/services/feeds/photos_public.gne?id=15738836@N00&lang=en-us&format=atom",
  "from_sgn", "content", "sgn://flickr.com/?pk=15738836@N00", "http://www.flickr.com/photos/15738836@N00/",
  "from_sgn", "profile", "sgn://flickr.com/?pk=15738836@N00", "http://www.flickr.com/people/15738836@N00/",
  "to_sgn", "http://friendfeed.com/ade", "sgn://friendfeed.com/?ident=ade",
  "to_sgn", "http://www.friendfeed.com/ade", "sgn://friendfeed.com/?ident=ade",
  "to_sgn", "http://friendfeed.com/daveman692/comments", "sgn://friendfeed.com/?ident=daveman692",
  "to_sgn", "http://friendfeed.com/daveman692?num=30", "sgn://friendfeed.com/?ident=daveman692",
  "to_sgn", "http://friendfeed.com/daveman692?service=blog", "sgn://friendfeed.com/?ident=daveman692",
  "to_sgn", "http://friendfeed.com/daveman692?service=digg", "sgn://friendfeed.com/?ident=daveman692",
  "to_sgn", "http://friendfeed.com/daveman692?service=flickr", "sgn://friendfeed.com/?ident=daveman692",
  "to_sgn", "http://friendfeed.com/daveman692?service=magnolia", "sgn://friendfeed.com/?ident=daveman692",
  "to_sgn", "http://friendfeed.com/daveman692?service=pownce", "sgn://friendfeed.com/?ident=daveman692",
  "to_sgn", "http://friendfeed.com/daveman692?service=twitter", "sgn://friendfeed.com/?ident=daveman692",
  "to_sgn", "http://friendfeed.com/daveman692?service=upcoming", "sgn://friendfeed.com/?ident=daveman692",
  "from_sgn", "profile", "sgn://friendfeed.com/?ident=ade", "http://friendfeed.com/ade",
  "from_sgn", "atom", "sgn://friendfeed.com/?ident=ade", "http://friendfeed.com/ade?format=atom",
  "to_sgn", "http://www.google.com/reader/shared/12649763491721032377", "sgn://reader.google.com/?pk=12649763491721032377",
  "to_sgn", "http://www.google.com/reader/public/atom/user/12649763491721032377/state/com.google/broadcast", "sgn://reader.google.com/?pk=12649763491721032377",
  "from_sgn", "content", "sgn://reader.google.com/?pk=12649763491721032377", "http://www.google.com/reader/shared/12649763491721032377",
  "from_sgn", "atom", "sgn://reader.google.com/?pk=12649763491721032377", "http://www.google.com/reader/public/atom/user/12649763491721032377/state/com.google/broadcast",
  "to_sgn", "http://youtube.com/jsmarr", "sgn://youtube.com/?ident=jsmarr",
  "to_sgn", "http://www.youtube.com/user/jsmarr", "sgn://youtube.com/?ident=jsmarr",
  "to_sgn", "http://www.youtube.com/profile?user=bradfitztube", "sgn://youtube.com/?ident=bradfitztube",
  "from_sgn", "profile", "sgn://youtube.com/?ident=jsmarr", "http://youtube.com/user/jsmarr",
  "from_sgn", "rss", "sgn://youtube.com/?ident=jsmarr", "http://youtube.com/rss/user/jsmarr/videos.rss",
  "to_sgn", "http://www.dodgeball.com/user?uid=54155", "sgn://dodgeball.com/?pk=54155",
  "from_sgn", "profile", "sgn://dodgeball.com/?pk=54155", "http://www.dodgeball.com/user?uid=54155",
  "to_sgn", "http://picasaweb.google.com/bradley.j.fitzpatrick/", "sgn://picasaweb.google.com/?ident=bradley.j.fitzpatrick",
  "to_sgn", "http://picasaweb.google.com/bradley.j.FITZPATRICK/", "sgn://picasaweb.google.com/?ident=bradley.j.fitzpatrick",
  "to_sgn", "http://picasaweb.google.com/jsmarr", "sgn://picasaweb.google.com/?ident=jsmarr",
  "from_sgn", "profile", "sgn://picasaweb.google.com/?ident=jsmarr", "http://picasaweb.google.com/jsmarr",
  "from_sgn", "rss", "sgn://picasaweb.google.com/?ident=jsmarr", "http://picasaweb.google.com/data/feed/base/user/jsmarr?kind=album&alt=rss&hl=en_US&access=public",
  "to_sgn", "http://www.orkut.com/Profile.aspx?uid=123", "sgn://orkut.com/?pk=123",
  "from_sgn", "profile", "sgn://orkut.com/?pk=123", "http://www.orkut.com/Profile.aspx?uid=123",
  "to_sgn", "http://picasaweb.google.es/Abc.Def", "sgn://picasaweb.google.com/?ident=abc.def",
  "to_sgn", "http://picasaweb.google.hu/abcdef", "sgn://picasaweb.google.com/?ident=abcdef",
  "to_sgn", "http://www.picasaweb.google.hu/abcdef", "sgn://picasaweb.google.com/?ident=abcdef",
  "to_sgn", "http://api.hi5.com/rest/profile/foaf/87628233", "sgn://hi5.com/?pk=87628233",
  "to_sgn", "http://lindner.hi5.com/", "sgn://hi5.com/?ident=lindner",
  "to_sgn", "http://123455.hi5.com/", "sgn://hi5.com/?pk=123455",
  "to_sgn", "http://www.hi5.com/", "http://www.hi5.com/",
  "to_sgn", "http://api.hi5.com/", "http://api.hi5.com/",
  "to_sgn", "http://www.hi5.com/friend/profile/displayProfile.do?userid=127525866", "sgn://hi5.com/?pk=127525866",
  "to_sgn", "http://lindner.hi5.com/friend/profile/displayJournal.do?viewother=true&ownerId=87628233", "sgn://hi5.com/?pk=87628233",
  "to_sgn", "http://lindner.hi5.com/friend/photos/displayUserAlbum.do?viewother=true&ownerId=87628233", "sgn://hi5.com/?pk=87628233",
  "to_sgn", "http://bradfitz.hi5.com/friend/photos/displayUserAlbum.do?viewother=true&ownerId=87628233", "sgn://hi5.com/?pk=87628233",
  "to_sgn", "http://lindner.hi5.com/friend/87628233--Paul--Profile-html", "sgn://hi5.com/?pk=87628233",
  "to_sgn", "http://bradfitz.hi5.com/friend/87628233--Paul--Profile-html", "sgn://hi5.com/?pk=87628233",
  "to_sgn", "http://lindner.hi5.com/friend/87628233--Paul--Friends-html", "sgn://hi5.com/?pk=87628233",
  "to_sgn", "http://lindner.hi5.com/friend/profile/displayFriends.do?userid=87628233&offset=24", "sgn://hi5.com/?pk=87628233",
  "to_sgn", "http://bradfitz.hi5.com/friend/87628233--Paul--Friends-html", "sgn://hi5.com/?pk=87628233",
  "to_sgn", "http://lindner.hi5.com/friend/30399640--Dan--Profile-html", "sgn://hi5.com/?pk=30399640",
  "to_sgn", "http://www.hi5.com/friend/profile/displaySameProfile.do?userid=87628233", "sgn://hi5.com/?pk=87628233",
  "to_sgn", "http://www.hi5.com/friend/profile/displayHi5URL.do?nickname=koolby", "sgn://hi5.com/?ident=koolby",
  "to_sgn", "http://www.hi5.com/friend/profile/displayHi5URL.do?nickname=bradfitz", "sgn://hi5.com/?ident=bradfitz",
  "from_sgn", "content", "sgn://hi5.com/?pk=123", "http://www.hi5.com/friend/profile/displayProfile.do?userid=123",
  "from_sgn", "profile", "sgn://hi5.com/?pk=123", "http://www.hi5.com/friend/profile/displayProfile.do?userid=123",
  "from_sgn", "atom", "sgn://hi5.com/?pk=123", "http://api.hi5.com/rest/feed/journal/123",
  "from_sgn", "foaf", "sgn://hi5.com/?pk=87628233", "http://api.hi5.com/rest/profile/foaf/87628233",
  "from_sgn", "blog", "sgn://hi5.com/?pk=12345", "http://www.hi5.com/friend/profile/displayJournal.do?userid=12345",
  "from_sgn", "content", "sgn://hi5.com/?ident=bobfoo", "http://bobfoo.hi5.com/",
  "from_sgn", "profile", "sgn://hi5.com/?ident=bobfoo", "http://bobfoo.hi5.com/",
  "to_sgn", "http://www.last.fm/user/aa123/", "sgn://last.fm/?ident=aa123",
  "to_sgn", "http://www.last.fm/user/aa123", "sgn://last.fm/?ident=aa123",
  "to_sgn", "http://lastfm.excite.co.jp/user/SomeCaps/", "sgn://last.fm/?ident=somecaps",
  "to_sgn", "http://www.last.fm/user/after/addedevents/", "sgn://last.fm/?ident=after",
  "to_sgn", "http://www.lastfm.pl/user/foo/?setlang=pl", "sgn://last.fm/?ident=foo",
  "to_sgn", "http://www.lastfm.com.br/user/Steph-Tara/?setlang=tr", "sgn://last.fm/?ident=steph-tara",
  "to_sgn", "http://www.lastfm.com.tr/user/Steph-Tara/charts/?setlang=tr", "sgn://last.fm/?ident=steph-tara",
  "to_sgn", "http://cn.last.fm/user/Steph-Tara/neighbours/", "sgn://last.fm/?ident=steph-tara",
  "from_sgn", "profile", "sgn://last.fm/?ident=foo", "http://www.last.fm/user/foo/",
  "to_sgn", "http://brad.livejournal.com/", "sgn://livejournal.com/?ident=brad",
  "to_sgn", "http://brad.livejournal.com/profile", "sgn://livejournal.com/?ident=brad",
  "to_sgn", "http://brad.livejournal.com/data/foaf", "sgn://livejournal.com/?ident=brad",
  "to_sgn", "http://brad.livejournal.com/data/rss", "sgn://livejournal.com/?ident=brad",
  "to_sgn", "http://brad.livejournal.com/data/atom", "sgn://livejournal.com/?ident=brad",
  "from_sgn", "content", "sgn://livejournal.com/?ident=brad", "http://brad.livejournal.com/",
  "to_sgn", "http://a-b.livejournal.com/", "sgn://livejournal.com/?ident=a_b",
  "to_sgn", "http://a-b.livejournal.com/profile", "sgn://livejournal.com/?ident=a_b",
  "from_sgn", "content", "sgn://livejournal.com/?ident=a_b", "http://a-b.livejournal.com/",
  "from_sgn", "content", "sgn://livejournal.com/?ident=_underscores_", "http://www.livejournal.com/~_underscores_/",
  "to_sgn", "http://users.livejournal.com/_underscores_/", "sgn://livejournal.com/?ident=_underscores_",
  "to_sgn", "http://users.livejournal.com/_underscores_/profile", "sgn://livejournal.com/?ident=_underscores_",
  "to_sgn", "http://users.livejournal.com/_underscores_", "sgn://livejournal.com/?ident=_underscores_",
  "to_sgn", "http://users.livejournal.com/_u_/profile", "sgn://livejournal.com/?ident=_u_",
  "to_sgn", "http://community.livejournal.com/linux/profile", "sgn://livejournal.com/?ident=linux",
  "to_sgn", "http://community.livejournal.com/linux/", "sgn://livejournal.com/?ident=linux",
  "to_sgn", "http://community.livejournal.com/linux", "sgn://livejournal.com/?ident=linux",
  "to_sgn", "http://www.livejournal.com/~abc/", "sgn://livejournal.com/?ident=abc",
  "to_sgn", "http://www.livejournal.com/~abc", "sgn://livejournal.com/?ident=abc",
  "to_sgn", "http://livejournal.com/~abc/", "sgn://livejournal.com/?ident=abc",
  "to_sgn", "http://livejournal.com/~abc", "sgn://livejournal.com/?ident=abc",
  "to_sgn", "http://livejournal.com/users/bob", "sgn://livejournal.com/?ident=bob",
  "to_sgn", "http://livejournal.com/users/bob/", "sgn://livejournal.com/?ident=bob",
  "from_sgn", "rss", "sgn://livejournal.com/?ident=abc", "http://abc.livejournal.com/data/rss",
  "from_sgn", "atom", "sgn://livejournal.com/?ident=abc", "http://abc.livejournal.com/data/atom",
  "from_sgn", "foaf", "sgn://livejournal.com/?ident=abc", "http://abc.livejournal.com/data/foaf",
  "from_sgn", "openid", "sgn://livejournal.com/?ident=abc", "http://abc.livejournal.com/",
  "from_sgn", "openid", "sgn://livejournal.com/?ident=abc", "http://abc.livejournal.com/",
  "to_sgn", "http://www.livejournal.com/userinfo.bml?userid=123&t=I", "sgn://livejournal.com/?pk=123",
  "to_sgn", "http://www.livejournal.com/userinfo.bml?userid=123", "sgn://livejournal.com/?pk=123",
  "to_sgn", "http://www.livejournal.com/userinfo.bml?user=bob", "sgn://livejournal.com/?ident=bob",
  "to_sgn", "http://www.livejournal.com/userinfo.bml?user=bob&mode=full", "sgn://livejournal.com/?ident=bob",
  "from_sgn", "profile", "sgn://livejournal.com/?ident=bob", "http://bob.livejournal.com/profile",
  "to_sgn", "http://www.meetup.com/members/2949792/", "sgn://meetup.com/?pk=2949792",
  "to_sgn", "http://coffee.meetup.com/171/members/2949792/?gj=sj3", "sgn://meetup.com/?pk=2949792",
  "to_sgn", "http://coffee.meetup.com/171/members/2949792/", "sgn://meetup.com/?pk=2949792",
  "to_sgn", "http://www.meetup.com/members/65", "sgn://meetup.com/?pk=65",
  "to_sgn", "http://www.meetup.com/members/65/", "sgn://meetup.com/?pk=65",
  "to_sgn", "http://MEETup.com/members/65", "sgn://meetup.com/?pk=65",
  "to_sgn", "http://meetup.com/members/65/", "sgn://meetup.com/?pk=65",
  "from_sgn", "profile", "sgn://meetup.com/?pk=65", "http://www.meetup.com/members/65/",
  "to_sgn", "http://myspace.com/foobar", "sgn://myspace.com/?ident=foobar",
  "to_sgn", "http://www.myspace.com/foobar", "sgn://myspace.com/?ident=foobar",
  "to_sgn", "http://myspace.com/foobar/", "sgn://myspace.com/?ident=foobar",
  "to_sgn", "http://profile.myspace.com/37715961", "sgn://myspace.com/?pk=37715961",
  "to_sgn", "http://profile.myspace.com/uhhhh_freakin_idiot", "sgn://myspace.com/?ident=uhhhh_freakin_idiot",
  "to_sgn", "http://profile.myspace.com/k93", "sgn://myspace.com/?ident=k93",
  "to_sgn", "http://www.myspace.com/index.cfm?fuseaction=user.viewprofile&friendid=73394553", "sgn://myspace.com/?pk=73394553",
  "to_sgn", "http://profile.myspace.com/index.cfm?fuseaction=user.viewprofile&friendid=73394553", "sgn://myspace.com/?pk=73394553",
  "to_sgn", "http://blog.myspace.com/index.cfm?fuseaction=blog.ListAll&friendID=64410858", "sgn://myspace.com/?pk=64410858",
  "to_sgn", "http://blog.myspace.com/index.cfm?fuseaction=blog.ConfirmSubscribe&friendID=64410858", "sgn://myspace.com/?pk=64410858",
  "to_sgn", "http://profile.myspace.com/index.cfm?fuseaction=user.viewProfile&friendID=34718576", "sgn://myspace.com/?pk=34718576",
  "from_sgn", "profile", "sgn://myspace.com/?pk=123", "http://profile.myspace.com/index.cfm?fuseaction=user.viewprofile&friendid=123",
  "from_sgn", "blog", "sgn://myspace.com/?pk=123", "http://blog.myspace.com/index.cfm?fuseaction=blog.ListAll&friendID=123",
  "from_sgn", "rss", "sgn://myspace.com/?pk=123", "http://blog.myspace.com/blog/rss.cfm?friendID=123",
  "from_sgn", "profile", "sgn://myspace.com/?ident=foobar", "http://myspace.com/foobar",
  "from_sgn", "content", "sgn://myspace.com/?ident=foobar", "http://myspace.com/foobar",
  "to_sgn", "xmpp:foo%40bar.com", "xmpp:foo@bar.com",
  "to_sgn", "jabber:foo%40bar.com", "xmpp:foo@bar.com",
  "to_sgn", "Xmpp:foo@bar.com", "xmpp:foo@bar.com",
  "to_sgn", "jabber:foo@bar.com", "xmpp:foo@bar.com",
  "to_sgn", "Mailto:brad%40bar.com", "mailto:brad@bar.com",
  "to_sgn", "http://digg.com/users/foobar", "sgn://digg.com/?ident=foobar",
  "to_sgn", "http://digg.com/users/foobar/", "sgn://digg.com/?ident=foobar",
  "from_sgn", "profile", "sgn://digg.com/?ident=foobar", "http://digg.com/users/foobar/",
  "from_sgn", "rss", "sgn://digg.com/?ident=foobar", "http://digg.com/rss/foobar/index2.xml",
  "to_sgn", "http://pownce.com/a", "sgn://pownce.com/?ident=a",
  "to_sgn", "http://pownce.com/A", "sgn://pownce.com/?ident=a",
  "to_sgn", "http://pownce.com/A/", "sgn://pownce.com/?ident=a",
  "to_sgn", "http://pownce.com/A/public/", "sgn://pownce.com/?ident=a",
  "to_sgn", "http://pownce.com/A/public/with_friends", "sgn://pownce.com/?ident=a",
  "to_sgn", "http://pownce.com/bob/foaf/", "sgn://pownce.com/?ident=bob",
  "from_sgn", "profile", "sgn://pownce.com/?ident=a", "http://pownce.com/a",
  "from_sgn", "rss", "sgn://pownce.com/?ident=a", "http://pownce.com/feeds/public/a.rss",
  "from_sgn", "atom", "sgn://pownce.com/?ident=a", "http://pownce.com/feeds/public/a.atom",
  "to_sgn", "http://bradfitz.jaiku.com/", "sgn://jaiku.com/?ident=bradfitz",
  "to_sgn", "http://BRADFITZ.JAIKU.COM/", "sgn://jaiku.com/?ident=bradfitz",
  "from_sgn", "profile", "sgn://jaiku.com/?ident=bradfitz", "http://bradfitz.jaiku.com/",
  "from_sgn", "rss", "sgn://jaiku.com/?ident=bradfitz", "http://bradfitz.jaiku.com/feed/rss",
  "to_sgn", "http://linkedin.com/in/foobar", "sgn://linkedin.com/?ident=foobar",
  "to_sgn", "http://linkedin.com/in/foobar/", "sgn://linkedin.com/?ident=foobar",
  "to_sgn", "http://www.linkedin.com/in/foobar/", "sgn://linkedin.com/?ident=foobar",
  "to_sgn", "http://www.linkedin.com/in/foobar", "sgn://linkedin.com/?ident=foobar",
  "from_sgn", "profile", "sgn://linkedin.com/?ident=foobar", "http://www.linkedin.com/in/foobar",
  "to_sgn", "http://ma.gnolia.com/people/daveman692", "sgn://ma.gnolia.com/?ident=daveman692",
  "to_sgn", "http://ma.gnolia.com/people/daveman692/", "sgn://ma.gnolia.com/?ident=daveman692",
  "from_sgn", "profile", "sgn://ma.gnolia.com/?ident=daveman692", "http://ma.gnolia.com/people/daveman692",
  "from_sgn", "rss", "sgn://ma.gnolia.com/?ident=daveman692", "http://ma.gnolia.com/rss/full/people/daveman692",
  "to_sgn", "http://mugshot.org/person?who=7ACcH9gn7zv4YG", "sgn://mugshot.org/?ident=7ACcH9gn7zv4YG",
  "from_sgn", "profile", "sgn://mugshot.org/?ident=7ACcH9gn7zv4YG", "http://mugshot.org/person?who=7ACcH9gn7zv4YG",
  "to_sgn", "http://www.ziki.com/en/people/bob", "sgn://ziki.com/?ident=bob",
  "to_sgn", "http://www.ziki.com/fr/people/bob/", "sgn://ziki.com/?ident=bob",
  "to_sgn", "http://www.ziki.com/fr/people/bob/extrastuff", "sgn://ziki.com/?ident=bob",
  "from_sgn", "profile", "sgn://ziki.com/?ident=bob", "http://www.ziki.com/people/bob",
  "to_sgn", "http://foo.wordpress.com/", "sgn://wordpress.com/?ident=foo",
  "to_sgn", "http://www.foo.wordpress.com/", "sgn://wordpress.com/?ident=foo",
  "from_sgn", "blog", "sgn://wordpress.com/?ident=foo", "http://foo.wordpress.com/",
  "to_sgn", "http://del.icio.us/jsmarr", "sgn://del.icio.us/?ident=jsmarr",
  "to_sgn", "http://delicious.com/jsmarr", "sgn://del.icio.us/?ident=jsmarr",
  "from_sgn", "profile", "sgn://del.icio.us/?ident=jsmarr", "http://del.icio.us/jsmarr",
  "from_sgn", "rss", "sgn://del.icio.us/?ident=jsmarr", "http://del.icio.us/rss/jsmarr",
  "to_sgn", "http://community.webshots.com/user/bob", "sgn://webshots.com/?ident=bob",
  "from_sgn", "profile", "sgn://webshots.com/?ident=bob", "http://community.webshots.com/user/bob",
  "from_sgn", "rss", "sgn://webshots.com/?ident=bob", "http://community.webshots.com/rss?contentType=rss&type=user&value=bob",
  "to_sgn", "http://jsmarr.smugmug.com", "sgn://smugmug.com/?ident=jsmarr",
  "from_sgn", "profile", "sgn://smugmug.com/?ident=jsmarr", "http://jsmarr.smugmug.com/",
  "from_sgn", "atom", "sgn://smugmug.com/?ident=jsmarr", "http://www.smugmug.com/hack/feed.mg?Type=nicknameRecentPhotos&Data=jsmarr&format=atom03",
  "to_sgn", "http://bradfitz.tumblr.com/", "sgn://tumblr.com/?ident=bradfitz",
  "from_sgn", "profile", "sgn://tumblr.com/?ident=bradfitz", "http://bradfitz.tumblr.com/",
  "from_sgn", "rss", "sgn://tumblr.com/?ident=bradfitz", "http://bradfitz.tumblr.com/rss",
  "to_sgn", "http://xanga.com/a/", "sgn://xanga.com/?ident=a",
  "from_sgn", "profile", "sgn://xanga.com/?ident=a", "http://xanga.com/a",
  "from_sgn", "rss", "sgn://xanga.com/?ident=a", "http://xanga.com/a/rss",
  "to_sgn", "http://360.yahoo.com/a/", "sgn://360.yahoo.com/?ident=a",
  "from_sgn", "profile", "sgn://360.yahoo.com/?ident=a", "http://360.yahoo.com/a",
  "from_sgn", "rss", "sgn://360.yahoo.com/?ident=a", "http://blog.360.yahoo.com/a",
  "to_sgn", "http://bradfitz.spaces.live.com/", "sgn://spaces.live.com/?ident=bradfitz",
  "from_sgn", "profile", "sgn://spaces.live.com/?ident=bradfitz", "http://bradfitz.spaces.live.com",
  "from_sgn", "rss", "sgn://spaces.live.com/?ident=bradfitz", "http://bradfitz.spaces.live.com/feed.rss",
  "to_sgn", "http://bradfitz.stumbleupon.com/", "sgn://stumbleupon.com/?ident=bradfitz",
  "from_sgn", "profile", "sgn://stumbleupon.com/?ident=bradfitz", "http://bradfitz.stumbleupon.com",
  "from_sgn", "rss", "sgn://stumbleupon.com/?ident=bradfitz", "http://www.stumbleupon.com/syndicate.php?stumbler=bradfitz",
  "to_sgn", "http://www.travelpod.com/members/foobar", "sgn://travelpod.com/?ident=foobar",
  "to_sgn", "http://travelpod.com/members/foobar/", "sgn://travelpod.com/?ident=foobar",
  "from_sgn", "profile", "sgn://travelpod.com/?ident=foobar", "http://travelpod.com/members/foobar",
  "from_sgn", "rss", "sgn://travelpod.com/?ident=foobar", "http://travelpod.com/syndication/rss/foobar",
  "to_sgn", "http://www.imageshack.us/user/foobar", "sgn://imageshack.us/?ident=foobar",
  "to_sgn", "http://imageshack.us/user/foobar/", "sgn://imageshack.us/?ident=foobar",
  "from_sgn", "profile", "sgn://imageshack.us/?ident=foobar", "http://profile.imageshack.us/user/foobar",
  "from_sgn", "rss", "sgn://imageshack.us/?ident=foobar", "http://rss.imageshack.us/user/foobar/rss/",
  "to_sgn", "http://www.bloglines.com/blog/jsmarr", "sgn://bloglines.com/?ident=jsmarr",
  "to_sgn", "http://www.bloglines.com/blog/jsmarr/rss", "sgn://bloglines.com/?ident=jsmarr",
  "to_sgn", "http://www.bloglines.com/public/jsmarr", "sgn://bloglines.com/?ident=jsmarr",
  "from_sgn", "profile", "sgn://bloglines.com/?ident=jsmarr", "http://www.bloglines.com/blog/jsmarr",
  "from_sgn", "rss", "sgn://bloglines.com/?ident=jsmarr", "http://www.bloglines.com/blog/jsmarr/rss",
  "to_sgn", "http://upcoming.yahoo.com/user/75587/", "sgn://upcoming.yahoo.com/?pk=75587",
  "to_sgn", "http://upcoming.org/user/75587/", "sgn://upcoming.yahoo.com/?pk=75587",
  "from_sgn", "profile", "sgn://upcoming.yahoo.com/?pk=75587", "http://upcoming.yahoo.com/user/75587/",
  "from_sgn", "rss", "sgn://upcoming.yahoo.com/?pk=75587", "http://upcoming.yahoo.com/syndicate/v2/my_events/75587",
  "to_sgn", "http://www.socializr.com/user/jsmarr", "sgn://socializr.com/?ident=jsmarr",
  "to_sgn", "http://www.socializr.com/rss/user/jsmarr/rss.xml", "sgn://socializr.com/?ident=jsmarr",
  "from_sgn", "profile", "sgn://socializr.com/?ident=jsmarr", "http://www.socializr.com/user/jsmarr",
  "from_sgn", "rss", "sgn://socializr.com/?ident=jsmarr", "http://www.socializr.com/rss/user/jsmarr/rss.xml",
  "to_sgn", "http://www.socializr.com/user/12345", "sgn://socializr.com/?pk=12345",
  "from_sgn", "profile", "sgn://socializr.com/?pk=12345", "http://www.socializr.com/user/12345",
  "from_sgn", "rss", "sgn://socializr.com/?pk=12345", "http://www.socializr.com/rss/user/12345/rss.xml",
  "to_sgn", "http://bebo.com/jsmarr", "sgn://bebo.com/?ident=jsmarr",
  "to_sgn", "http://bebo.com/Profile.jsp?MemberId=12345", "sgn://bebo.com/?pk=12345",
  "from_sgn", "profile", "sgn://bebo.com/?ident=jsmarr", "http://bebo.com/jsmarr",
  "from_sgn", "profile", "sgn://bebo.com/?pk=12345", "http://bebo.com/Profile.jsp?MemberId=12345",
  "from_sgn", "rss", "sgn://bebo.com/?pk=12345", "http://bebo.com/api/BlogRss.jsp?MemberId=12345",
  "to_sgn", "http://reddit.com/user/jsmarr", "sgn://reddit.com/?ident=jsmarr",
  "to_sgn", "http://reddit.com/user/jsmarr/submitted.rss", "sgn://reddit.com/?ident=jsmarr",
  "from_sgn", "profile", "sgn://reddit.com/?ident=jsmarr", "http://reddit.com/user/jsmarr",
  "from_sgn", "rss", "sgn://reddit.com/?ident=jsmarr", "http://reddit.com/user/jsmarr/submitted.rss",
  "to_sgn", "http://www.ilike.com/user/jsmarr", "sgn://ilike.com/?ident=jsmarr",
  "to_sgn", "http://ilike.com/user/jsmarr/songs_ilike.rss", "sgn://ilike.com/?ident=jsmarr",
  "from_sgn", "profile", "sgn://ilike.com/?ident=jsmarr", "http://www.ilike.com/user/jsmarr",
  "from_sgn", "rss", "sgn://ilike.com/?ident=jsmarr", "http://www.ilike.com/user/jsmarr/songs_ilike.rss",
  "to_sgn", "http://www.zooomr.com/photos/jsmarr", "sgn://zooomr.com/?ident=jsmarr",
  "to_sgn", "http://www.zooomr.com/people/jsmarr", "sgn://zooomr.com/?ident=jsmarr",
  "from_sgn", "profile", "sgn://zooomr.com/?ident=jsmarr", "http://www.zooomr.com/people/jsmarr",
  "from_sgn", "rss", "sgn://zooomr.com/?ident=jsmarr", "http://www.zooomr.com/services/feeds/public_photos/?id=jsmarr&format=rss_200",
  "to_sgn", "http://bradfitz.multiply.com/", "sgn://multiply.com/?ident=bradfitz",
  "from_sgn", "profile", "sgn://multiply.com/?ident=bradfitz", "http://bradfitz.multiply.com/",
  "from_sgn", "rss", "sgn://multiply.com/?ident=bradfitz", "http://bradfitz.multiply.com/feed.rss",
  "to_sgn", "http://btrott.vox.com/", "sgn://vox.com/?ident=btrott",
  "to_sgn", "http://btrott.vox.com/profile/foaf.rdf", "sgn://vox.com/?ident=btrott",
  "to_sgn", "http://btrott.vox.com/profile/", "sgn://vox.com/?ident=btrott",
  "to_sgn", "http://btrott.vox.com/library/audio/6a00b8ea0714f01bc000e398d429800003.html", "sgn://vox.com/?ident=btrott",
  "from_sgn", "profile", "sgn://vox.com/?ident=btrott", "http://btrott.vox.com/profile/",
  "from_sgn", "foaf", "sgn://vox.com/?ident=btrott", "http://btrott.vox.com/profile/foaf.rdf",
  "from_sgn", "atom", "sgn://vox.com/?ident=btrott", "http://btrott.vox.com/library/atom-full.xml",
  "from_sgn", "rss", "sgn://vox.com/?ident=btrott", "http://btrott.vox.com/library/rss-full.xml",
  "to_sgn", "http://www.dopplr.com/traveller/bradfitz/", "sgn://dopplr.com/?ident=bradfitz",
  "to_sgn", "http://dopplr.com/traveller/bradfitz/", "sgn://dopplr.com/?ident=bradfitz",
  "to_sgn", "http://www.dopplr.com/traveller/bradfitz", "sgn://dopplr.com/?ident=bradfitz",
  "to_sgn", "http://www.dopplr.com/traveller/bradfitz/something", "sgn://dopplr.com/?ident=bradfitz",
  "from_sgn", "profile", "sgn://dopplr.com/?ident=bradfitz", "http://www.dopplr.com/traveller/bradfitz",
  "to_sgn", "http://c2.com/cgi/wiki?AdewaleOshineye", "sgn://c2.com/?ident=AdewaleOshineye",
  "from_sgn", "profile", "sgn://c2.com/?ident=AdewaleOshineye", "http://c2.com/cgi/wiki?AdewaleOshineye",
  "to_sgn", "http://bookshelved.org/cgi-bin/wiki.pl?AdewaleOshineye", "sgn://bookshelved.org/?ident=AdewaleOshineye",
  "from_sgn", "profile", "sgn://bookshelved.org/?ident=AdewaleOshineye", "http://bookshelved.org/cgi-bin/wiki.pl?AdewaleOshineye",
  "to_sgn", "http://xpdeveloper.net/xpdwiki/Wiki.jsp?page=AdewaleOshineye", "sgn://xpdeveloper.net/?ident=AdewaleOshineye",
  "from_sgn", "profile", "sgn://xpdeveloper.net/?ident=AdewaleOshineye", "http://xpdeveloper.net/xpdwiki/Wiki.jsp?page=AdewaleOshineye",
  "to_sgn", "http://usemod.com/cgi-bin/mb.pl?SunirShah", "sgn://usemod.com/?ident=SunirShah",
  "from_sgn", "profile", "sgn://usemod.com/?ident=SunirShah", "http://usemod.com/cgi-bin/mb.pl?SunirShah",
  "to_sgn", "http://www.advogato.org/person/bradfitz", "sgn://advogato.org/?ident=bradfitz",
  "to_sgn", "http://www.advogato.org/person/bradfitz/", "sgn://advogato.org/?ident=bradfitz",
  "to_sgn", "http://www.advogato.org/person/bradfitz/foaf.rdf", "sgn://advogato.org/?ident=bradfitz",
  "to_sgn", "http://www.advogato.org/person/bradfitz/foaf.rdf#me", "sgn://advogato.org/?ident=bradfitz",
  "from_sgn", "foaf", "sgn://advogato.org/?ident=bradfitz", "http://www.advogato.org/person/bradfitz/foaf.rdf",
  "from_sgn", "profile", "sgn://advogato.org/?ident=bradfitz", "http://www.advogato.org/person/bradfitz/",
  "to_sgn", "http://bob.weeloop.com", "sgn://weeloop.com/?ident=bob",
  "to_sgn", "http://bob.weeloop.com/profile", "sgn://weeloop.com/?ident=bob",
  "to_sgn", "http://bob.weeloop.com/api/post?mimeType=application/rss+xml", "sgn://weeloop.com/?ident=bob",
  "to_sgn", "http://bob.weeloop.com/api/post?mimeType=application/atom+xml", "sgn://weeloop.com/?ident=bob",
  "to_sgn", "http://bob.weeloop.com/foaf.rdf", "sgn://weeloop.com/?ident=bob",
  "from_sgn", "foaf", "sgn://weeloop.com/?ident=bob", "http://bob.weeloop.com/foaf.rdf",
  "from_sgn", "profile", "sgn://weeloop.com/?ident=bob", "http://bob.weeloop.com/profile",
  "from_sgn", "atom", "sgn://weeloop.com/?ident=bob", "http://bob.weeloop.com/api/post?mimeType=application/atom+xml",
  "to_sgn", "http://www.furl.net/members/jsmarr", "sgn://furl.net/?ident=jsmarr",
  "to_sgn", "http://furl.net/members/jsmarr/rss.xml", "sgn://furl.net/?ident=jsmarr",
  "from_sgn", "profile", "sgn://furl.net/?ident=jsmarr", "http://www.furl.net/members/jsmarr",
  "from_sgn", "rss", "sgn://furl.net/?ident=jsmarr", "http://www.furl.net/members/jsmarr/rss.xml",
  "to_sgn", "http://www.dailymotion.com/jsmarr", "sgn://dailymotion.com/?ident=jsmarr",
  "to_sgn", "http://dailymotion.com/jsmarr", "sgn://dailymotion.com/?ident=jsmarr",
  "to_sgn", "http://www.dailymotion.com/rss/jsmarr/1", "sgn://dailymotion.com/?ident=jsmarr",
  "from_sgn", "profile", "sgn://dailymotion.com/?ident=jsmarr", "http://www.dailymotion.com/jsmarr",
  "from_sgn", "rss", "sgn://dailymotion.com/?ident=jsmarr", "http://www.dailymotion.com/rss/jsmarr/1",
  "to_sgn", "http://www.vimeo.com/jsmarr", "sgn://vimeo.com/?ident=jsmarr",
  "to_sgn", "http://vimeo.com/jsmarr", "sgn://vimeo.com/?ident=jsmarr",
  "to_sgn", "http://www.vimeo.com/jsmarr/videos/rss", "sgn://vimeo.com/?ident=jsmarr",
  "from_sgn", "profile", "sgn://vimeo.com/?ident=jsmarr", "http://www.vimeo.com/jsmarr",
  "from_sgn", "rss", "sgn://vimeo.com/?ident=jsmarr", "http://www.vimeo.com/jsmarr/videos/rss",
  "to_sgn", "http://www.disqus.com/people/jsmarr", "sgn://disqus.com/?ident=jsmarr",
  "to_sgn", "http://disqus.com/people/jsmarr/comments.rss", "sgn://disqus.com/?ident=jsmarr",
  "from_sgn", "profile", "sgn://disqus.com/?ident=jsmarr", "http://www.disqus.com/people/jsmarr",
  "from_sgn", "rss", "sgn://disqus.com/?ident=jsmarr", "http://www.disqus.com/people/jsmarr/comments.rss",
  "to_sgn", "http://www.rateitall.com/jsmarr", "sgn://rateitall.com/?ident=jsmarr",
  "to_sgn", "http://www.rateitall.com/usercommentsrss.aspx?RI=jsmarr", "sgn://rateitall.com/?ident=jsmarr",
  "to_sgn", "http://www.rateitall.com/usercommentsrss.aspx?RI=12345", "sgn://rateitall.com/?pk=12345",
  "from_sgn", "profile", "sgn://rateitall.com/?ident=jsmarr", "http://www.rateitall.com/jsmarr",
  "from_sgn", "rss", "sgn://rateitall.com/?ident=jsmarr", "http://www.rateitall.com/usercommentsrss.aspx?RI=jsmarr",
  "from_sgn", "rss", "sgn://rateitall.com/?pk=12345", "http://www.rateitall.com/usercommentsrss.aspx?RI=12345",
  "to_sgn", "http://www.slideshare.net/jsmarr", "sgn://slideshare.net/?ident=jsmarr",
  "to_sgn", "http://slideshare.net/rss/user/jsmarr", "sgn://slideshare.net/?ident=jsmarr",
  "from_sgn", "profile", "sgn://slideshare.net/?ident=jsmarr", "http://www.slideshare.net/jsmarr",
  "from_sgn", "rss", "sgn://slideshare.net/?ident=jsmarr", "http://www.slideshare.net/rss/user/jsmarr",
  "to_sgn", "http://blog.sina.com.cn/jsmarr", "sgn://blog.sina.com.cn/?ident=jsmarr",
  "to_sgn", "http://blog.sina.com.cn/rss/jsmarr.xml", "sgn://blog.sina.com.cn/?ident=jsmarr",
  "from_sgn", "profile", "sgn://blog.sina.com.cn/?ident=jsmarr", "http://blog.sina.com.cn/jsmarr",
  "from_sgn", "rss", "sgn://blog.sina.com.cn/?ident=jsmarr", "http://blog.sina.com.cn/rss/jsmarr.xml",
  "to_sgn", "http://hi.baidu.com/jsmarr", "sgn://hi.baidu.com/?ident=jsmarr",
  "to_sgn", "http://hi.baidu.com/jsmarr/rss", "sgn://hi.baidu.com/?ident=jsmarr",
  "from_sgn", "profile", "sgn://hi.baidu.com/?ident=jsmarr", "http://hi.baidu.com/jsmarr",
  "from_sgn", "rss", "sgn://hi.baidu.com/?ident=jsmarr", "http://hi.baidu.com/jsmarr/rss",
  "to_sgn", "http://jsmarr.blogbus.com/", "sgn://blogbus.com/?ident=jsmarr",
  "to_sgn", "http://jsmarr.blogbus.com/index.rdf", "sgn://blogbus.com/?ident=jsmarr",
  "from_sgn", "profile", "sgn://blogbus.com/?ident=jsmarr", "http://jsmarr.blogbus.com/",
  "from_sgn", "rss", "sgn://blogbus.com/?ident=jsmarr", "http://jsmarr.blogbus.com/index.rdf",
  "pair", "spin.de", "Warp", "sgn://spin.de/?ident=warp",
  "to_sgn", "http://www.spin.de/hp/Warp", "sgn://spin.de/?ident=warp",
  "to_sgn", "http://www.spin.de/hp/warp", "sgn://spin.de/?ident=warp",
  "to_sgn", "http://www.spin.de/hp/Warp/", "sgn://spin.de/?ident=warp",
  "to_sgn", "http://www.spin.de/hp/Warp/blog", "sgn://spin.de/?ident=warp",
  "to_sgn", "http://www.spin.de/foaf/Warp", "sgn://spin.de/?ident=warp",
  "to_sgn", "http://www.spin.de/hp/xITO!!!/", "sgn://spin.de/?ident=xito!!!",
  "to_sgn", "http://www.spin.de/hp/*xordon*/", "sgn://spin.de/?ident=*xordon*",
  "to_sgn", "http://www.spin.de/hp/,62b", "sgn://spin.de/?pk=62b",
  "to_sgn", "http://www.spin.de/hp/,62b/blog", "sgn://spin.de/?pk=62b",
  "from_sgn", "foaf", "sgn://spin.de/?ident=warp", "http://www.spin.de/foaf/warp",
  "from_sgn", "foaf", "sgn://spin.de/?pk=62b", "http://www.spin.de/foaf/,62b",
  "from_sgn", "profile", "sgn://spin.de/?ident=warp", "http://www.spin.de/hp/warp/",
  "from_sgn", "blog", "sgn://spin.de/?ident=warp", "http://www.spin.de/hp/warp/blog",
  "to_sgn", "http://www.threadless.com/profile/149253/Aunalis", "sgn://threadless.com/?ident=149253/aunalis",
  "to_sgn", "http://www.threadless.com/profile/149253", "sgn://threadless.com/?pk=149253",
  "from_sgn", "profile", "sgn://threadless.com/?pk=149253", "http://www.threadless.com/profile/149253",
  "from_sgn", "profile", "sgn://threadless.com/?ident=149253/aunalis", "http://www.threadless.com/profile/149253/aunalis",
  "to_sgn", "http://www.threadless.com/rss/blog/149253/Aunalis", "sgn://threadless.com/?ident=149253/aunalis",
  "to_sgn", "http://www.threadless.com/rss/blog/149253", "sgn://threadless.com/?pk=149253",
  "from_sgn", "rss", "sgn://threadless.com/?ident=149253/aunalis", "http://www.threadless.com/rss/blog/149253/aunalis",
  "from_sgn", "rss", "sgn://threadless.com/?pk=149253", "http://www.threadless.com/rss/blog/149253",
  "to_sgn", "http://www.threadless.com/profile/149253/Aunalis/archive", "sgn://threadless.com/?ident=149253/aunalis",
  "to_sgn", "http://www.threadless.com/profile/149253/Aunalis/blogs", "sgn://threadless.com/?ident=149253/aunalis",
  "to_sgn", "http://www.threadless.com/profile/149253/Aunalis/blog/", "sgn://threadless.com/?ident=149253/aunalis",
  "to_sgn", "http://threadless.com/profile/226507/Legoman", "sgn://threadless.com/?ident=226507/legoman",
  "to_sgn", "http://media.threadless.com/profile/284208/Neiko", "sgn://threadless.com/?ident=284208/neiko",
  "from_sgn", "blog", "sgn://threadless.com/?ident=149253/aunalis", "http://www.threadless.com/profile/149253/aunalis/blogs",
  "to_sgn", "http://people.tribe.net/bayareadj/foaf", "sgn://tribe.net/?ident=bayareadj",
  "to_sgn", "http://people.tribe.net/bayareadj/", "sgn://tribe.net/?ident=bayareadj",
  "to_sgn", "http://people.tribe.net/bayareadj", "sgn://tribe.net/?ident=bayareadj",
  "to_sgn", "http://people.tribe.net/079d0f9a-ed4b-4d2d-8290-a65a3df32342", "sgn://tribe.net/?pk=079d0f9a-ed4b-4d2d-8290-a65a3df32342",
  "to_sgn", "http://people.tribe.net/079d0f9a-ed4b-4d2d-8290-a65a3df32342/foaf", "sgn://tribe.net/?pk=079d0f9a-ed4b-4d2d-8290-a65a3df32342",
  "to_sgn", "http://people.tribe.net/079d0f9a-ed4b-4d2d-8290-a65a3df32342/blog", "sgn://tribe.net/?pk=079d0f9a-ed4b-4d2d-8290-a65a3df32342",
  "to_sgn", "http://www.people.tribe.net/c72b358e-1f53-407e-aa98-5b18c70072e1/blog", "sgn://tribe.net/?pk=c72b358e-1f53-407e-aa98-5b18c70072e1",
  "from_sgn", "foaf", "sgn://tribe.net/?ident=bayareadj", "http://people.tribe.net/bayareadj/foaf",
  "from_sgn", "foaf", "sgn://tribe.net/?pk=079d0f9a-ed4b-4d2d-8290-a65a3df32342", "http://people.tribe.net/079d0f9a-ed4b-4d2d-8290-a65a3df32342/foaf",
  "from_sgn", "profile", "sgn://tribe.net/?ident=bayareadj", "http://people.tribe.net/bayareadj",
  "from_sgn", "profile", "sgn://tribe.net/?pk=079d0f9a-ed4b-4d2d-8290-a65a3df32342", "http://people.tribe.net/079d0f9a-ed4b-4d2d-8290-a65a3df32342",
  "to_sgn", "http://twitter.com/bob", "sgn://twitter.com/?ident=bob",
  "to_sgn", "http://twitter.com/Bob", "sgn://twitter.com/?ident=bob",
  "to_sgn", "http://twitter.com/Bob/", "sgn://twitter.com/?ident=bob",
  "to_sgn", "https://twitter.com/bob", "sgn://twitter.com/?ident=bob",
  "to_sgn", "https://twitter.com/BOB/", "sgn://twitter.com/?ident=bob",
  "to_sgn", "http://explore.twitter.com/bob/with_friends", "sgn://twitter.com/?ident=bob",
  "to_sgn", "http://greekshow.twitter.com/bob/with_friends", "sgn://twitter.com/?ident=bob",
  "from_sgn", "profile", "sgn://twitter.com/?ident=brad", "http://twitter.com/brad",
  "from_sgn", "rss", "sgn://twitter.com/?ident=brad", "http://twitter.com/statuses/user_timeline/brad.rss",
  "from_sgn", "atom", "sgn://twitter.com/?ident=brad", "http://twitter.com/statuses/user_timeline/brad.atom",
  "to_sgn", "http://twitter.com/statuses/user_timeline/BRAD.rss", "sgn://twitter.com/?ident=brad",
  "to_sgn", "http://twitter.com/statuses/user_timeline/1234.rss", "sgn://twitter.com/?pk=1234",
  "to_sgn", "http://jsmarr.yelp.com", "sgn://yelp.com/?ident=jsmarr",
  "to_sgn", "http://www.yelp.com/user_details?userid=Dk2IkchUjADbrC05sdsAVQ", "sgn://yelp.com/?pk=Dk2IkchUjADbrC05sdsAVQ",
  "from_sgn", "rss", "sgn://yelp.com/?pk=Dk2IkchUjADbrC05sdsAVQ", "http://www.yelp.com/syndicate/user/Dk2IkchUjADbrC05sdsAVQ/rss.xml",
  "from_sgn", "profile", "sgn://yelp.com/?pk=Dk2IkchUjADbrC05sdsAVQ", "http://www.yelp.com/user_details?userid=Dk2IkchUjADbrC05sdsAVQ",
  "from_sgn", "profile", "sgn://yelp.com/?ident=jsmarr", "http://jsmarr.yelp.com"
];
