// Auto-generated test data from sites/*.js test sections at bottom.
var nodemapper_tests = [
  ["urlToGraphNode", "http://www.flickr.com/people/crucially", "sgn://flickr.com/?ident=crucially"],
  ["urlToGraphNode", "http://www.flickr.com/people/crucially/", "sgn://flickr.com/?ident=crucially"],
  ["urlToGraphNode", "http://www.flickr.com/photos/crucially", "sgn://flickr.com/?ident=crucially"],
  ["urlToGraphNode", "http://www.flickr.com/photos/crucially/", "sgn://flickr.com/?ident=crucially"],
  ["urlToGraphNode", "http://www.flickr.com/photos/15738836@N00/", "sgn://flickr.com/?pk=15738836@N00"],
  ["urlToGraphNode", "http://www.flickr.com/people/15738836@N00/", "sgn://flickr.com/?pk=15738836@N00"],
  ["urlFromGraphNode", "sgn://flickr.com/?ident=crucially", "profile", "http://www.flickr.com/people/crucially/"],
  ["urlToGraphNode", "http://www.flickr.com/people/crucially/", "sgn://flickr.com/?ident=crucially"],
  ["urlFromGraphNode", "sgn://flickr.com/?ident=crucially", "content", "http://www.flickr.com/photos/crucially/"],
  ["urlToGraphNode", "http://www.flickr.com/photos/crucially/", "sgn://flickr.com/?ident=crucially"],
  ["urlFromGraphNode", "sgn://flickr.com/?ident=crucially", "addfriend", "http://www.flickr.com/people/crucially/relationship/"],
  ["urlToGraphNode", "http://www.flickr.com/people/crucially/relationship/", "sgn://flickr.com/?ident=crucially"],
  ["urlFromGraphNode", "sgn://flickr.com/?pk=15738836@N00", "rss", "http://api.flickr.com/services/feeds/photos_public.gne?id=15738836@N00&lang=en-us&format=rss_200"],
  ["urlToGraphNode", "http://api.flickr.com/services/feeds/photos_public.gne?id=15738836@N00&lang=en-us&format=rss_200", "sgn://flickr.com/?pk=15738836@N00"],
  ["urlFromGraphNode", "sgn://flickr.com/?pk=15738836@N00", "atom", "http://api.flickr.com/services/feeds/photos_public.gne?id=15738836@N00&lang=en-us&format=atom"],
  ["urlToGraphNode", "http://api.flickr.com/services/feeds/photos_public.gne?id=15738836@N00&lang=en-us&format=atom", "sgn://flickr.com/?pk=15738836@N00"],
  ["urlFromGraphNode", "sgn://flickr.com/?pk=15738836@N00", "content", "http://www.flickr.com/photos/15738836@N00/"],
  ["urlToGraphNode", "http://www.flickr.com/photos/15738836@N00/", "sgn://flickr.com/?pk=15738836@N00"],
  ["urlFromGraphNode", "sgn://flickr.com/?pk=15738836@N00", "profile", "http://www.flickr.com/people/15738836@N00/"],
  ["urlToGraphNode", "http://www.flickr.com/people/15738836@N00/", "sgn://flickr.com/?pk=15738836@N00"],
  ["urlToGraphNode", "http://www.flickr.com/photos/84536344%40N00/", "sgn://flickr.com/?pk=84536344@N00"],
  ["pairToGraphNode", "flickr.com", "brad@danga.com", ""],
  ["urlToGraphNode", "http://friendfeed.com/daveman692?service=flickr", "sgn://friendfeed.com/?ident=daveman692"]
];
